# -Dspring.profiles.active=gae
spring:
  main:
    banner-mode: "off"
  messages:
    basename: i18n/messages
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxActive: 10
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
security:
  require-ssl: true
  basic:
    enabled: false
