spring.thymeleaf.cache: false
spring:
  datasource:
    url: ${DB_URL}?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: inyfdckdjiqsjy
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxTotal: 10
