# -Dspring.profiles.active=dev
spring.thymeleaf.cache: false
spring:
  main:
    banner-mode: "off"
  messages:
    basename: i18n/messages
  datasource:
#    url: ${DB_URL}?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxTotal: 10
  http:
    multipart:
      maxFileSize: 8MB
      maxRequestSize: 10MB
  servlet:
    multipart:
      maxFileSize: 8MB
      maxRequestSize: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
#logging.level.org.hibernate: DEBUG
