spring:
  datasource:
    url: ${DB_URL}
    username: inyfdckdjiqsjy
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
