# -Dspring.profiles.active=dev
spring.thymeleaf.cache: false
spring:
  main:
    banner-mode: "off"
  datasource:
#    url: ${DB_URL}?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.postgresql.Driver
    maxTotal: 10
  http:
    multipart:
      maxFileSize: 4MB
      maxRequestSize: 4MB
logging.level.org.hibernate: DEBUG
