var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]};
$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991},"es6-impl","es3");
$jscomp.polyfill("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991},"es6-impl","es3");$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(a,c,d){var b=this.length||0;0>c&&(c=Math.max(0,b+c));if(null==d||d>b)d=b;d=Number(d);0>d&&(d=Math.max(0,b+d));for(c=Number(c||0);c<d;c++)this[c]=a;return this}},"es6-impl","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6-impl","es3");
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.polyfill("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)$jscomp.owns(e,f)&&(a[f]=e[f])}return a}},"es6-impl","es3");var Matter=function(a,b,c){this.x=a;this.y=b;this.z=void 0===c?0:c;this.dy=this.h=this.w=0;this.dir=null;this.gravity=this.radian=0;this.speed=1};
$jscomp.global.Object.defineProperties(Matter.prototype,{width:{configurable:!0,enumerable:!0,get:function(){return this.w},set:function(a){this.w=a;this.hW=a/2}},height:{configurable:!0,enumerable:!0,get:function(){return this.h},set:function(a){this.h=a;this.hH=a/2}}});
var Actor=function(a,b,c){Matter.call(this,a,b,void 0===c?0:c);var d=this;this.region=new Region(this);this.height=this.width=16;this.animList=[];this.chamberList=[];this.hasBounds=!0;this.reaction=0;this.effectV=this.effectH=!0;this.hitPoint=1;this.absorbed=!1;this.score=0;this.walled=!1;this.recalculation();this.img=new Image;this.img.addEventListener("load",function(){d.width=d.img.width;d.height=d.img.height;d.recalculation()});this.fillStyle=null;this.sfx="sfx-explosion";this.sfxAbsorb="sfx-absorb";
this.enter()};$jscomp.inherits(Actor,Matter);Actor.prototype.recalculation=function(){var a=Field.Instance;if(a){var b=this.hasBounds?0:a.width;this.minX=-this.width-b;this.minY=-this.height-b;this.maxX=a.width+this.width+b;this.maxY=a.height+this.height+b}};Actor.prototype.enter=function(){this.explosion=0;this.isGone=!1};Actor.prototype.eject=function(){this.isGone=!0;this.x=Number.MIN_SAFE_INTEGER};
Actor.prototype.aim=function(a){if(a){var b=this.calcDistance(a);this.speed<b&&(this.dir=Math.atan2(a.y-this.y,a.x-this.x))}else this.dir=null;return this};Actor.prototype.closeGap=function(a){a=Math.trim(this.radian-Math.atan2(a.y-this.y,a.x-this.x));return Math.abs(a)<=Actor.DEG_STEP?0:0<a?-Actor.DEG_STEP:Actor.DEG_STEP};Actor.prototype.reactX=function(a){this.dir=Math.trim(this.dir+Math.PI)};Actor.prototype.reactY=function(a){this.y=a;this.dy*=-this.reaction;this.radian=Field.Instance.landform.getHorizontalAngle(this)};
Actor.prototype.trigger=function(a,b){b=void 0===b?!1:b;var c=this,d=[];this.chamberList.forEach(function(a){return a.probe()});if(this.triggered||b)this.triggered=!1,this.chamberList.forEach(function(b){(b=b.fire(c,a))&&d.push(b)});return d};
Actor.prototype.move=function(a){var b=this;if(0<this.explosion&&(this.explosion--,0==this.explosion)){this.eject();return}this.svX=this.x;this.svY=this.y;null!=this.dir&&(this.x+=Math.cos(this.dir)*this.speed,this.y+=Math.sin(this.dir)*this.speed);if(0!=this.gravity){var c=Field.Instance.landform.scanFloor(this),d=!1;0>this.gravity?(c+=this.hH,c<this.y?this.dy+=this.gravity:this.y<c&&(d=!0)):(c-=this.hH,this.y<c?this.dy+=this.gravity:c<this.y&&(d=!0));d&&(2*Landform.BRICK_WIDTH<Math.abs(this.y-c)?
this.reactX(c):this.reactY(c))}this.y+=this.dy*this.speed;this.animList.forEach(function(a){a.next(b.dir)});return this.trigger(a)};Actor.prototype.drawCircle=function(a){a.save();a.beginPath();a.fillStyle=this.fillStyle;a.arc(0,0,this.width,0,2*Math.PI,!1);a.fill();a.restore()};Actor.prototype.drawHitPoint=function(a){1E5>this.hitPoint&&(a.save(),a.fillStyle="white",a.fillText(this.hitPoint,0,20),a.restore())};
Actor.prototype.drawNormal=function(a){this.animList.forEach(function(b){b.draw(a)});0==this.animList.length&&this.fillStyle&&this.drawCircle(a)};Actor.prototype.drawExplosion=function(a){var b=this.explosion;a.save();a.fillStyle="rgba(255, 0, 0, 0.7)";a.beginPath();a.arc(0,0,b,0,Math.PI2,!1);a.fill();a.restore()};Actor.prototype.draw=function(a){this.isGone||(a.save(),a.translate(this.x,this.y),0<this.explosion?this.drawExplosion(a):this.drawNormal(a),a.restore())};
Actor.prototype.isHit=function(a){return this.isGone||0<this.explosion||0<a.explosion?!1:this.region.isHit(a.region)?(this.fate(a),a.fate(this),!0):!1};Actor.prototype.calcDistance=function(a){var b=this.x-a.x;a=this.y-a.y;return Math.sqrt(b*b+a*a)};Actor.prototype.fate=function(a){this.isGone||this.explosion||(this.hitPoint--,0<this.hitPoint?this.absorb(a):(this.explosion=Actor.MAX_EXPLOSION,a=Field.Instance.calcPan(this.x),AudioMixer.INSTANCE.play(this.sfx,.2,!1,a)))};
Actor.prototype.absorb=function(a){this.absorbed=!0;if(this.sfxAbsorb){var b=Field.Instance.ctx;b.fillStyle="rgba(255, 200, 0, 0.4)";b.save();b.translate(a.x,a.y);b.beginPath();b.arc(0,0,5,0,Math.PI2,!1);b.fill();b.restore();a=Field.Instance.calcPan(this.x);AudioMixer.INSTANCE.play(this.sfxAbsorb,.3,!1,a)}};$jscomp.global.Object.defineProperties(Actor.prototype,{anim:{configurable:!0,enumerable:!0,set:function(a){Array.isArray(a)?this.animList=a:this.animList=[a]}}});Actor.MAX_EXPLOSION=12;
Actor.DEG_STEP=Math.PI/180;var Animator=function(a,b,c,d,e){c=void 0===c?Animator.TYPE.ROTATION:c;this.actor=a;this.type=c;this.numX=void 0===d?1:d;this.numY=void 0===e?1:e;this.patNum=0;this.loadImage(a,b)};
Animator.prototype.loadImage=function(a,b){var c=this;(this.img=ImageManager.Instance.dic[b])?(this.width=this.img.width/this.numX,this.height=this.img.height/this.numY,this.hW=this.width/2,this.hH=this.height/2,a.width=this.width,a.height=this.height,a.recalculation()):(ImageManager.Instance.reserve([b]),this.img=new Image,this.img.onload=function(){c.width=c.img.width/c.numX;c.height=c.img.height/c.numY;c.hW=c.width/2;c.hH=c.height/2;a.width=c.width;a.height=c.height;a.recalculation()},this.img.src=
"/img/"+b)};
Animator.prototype.next=function(a){this.type&Animator.TYPE.V&&.1<Math.abs(this.patNum)&&(this.patNum=0>this.patNum?this.patNum+.1:this.patNum-.1);if(null!=a)if(this.type&Animator.TYPE.X)this.patNum+=.5*Math.cos(a),a=Math.floor(this.patNum),0>a?this.patNum=this.numX-.1:this.numX<=a&&(this.patNum=0);else if(this.type&Animator.TYPE.Y)this.patNum+=.5*Math.sin(a),a=Math.floor(this.patNum),0>a?this.patNum=this.numY-.1:this.numY<=a&&(this.patNum=0);else if(this.type&Animator.TYPE.V){var b=Math.floor(this.numY/2);
this.patNum+=Math.sin(a)/3;this.patNum<-b?this.patNum=-b:b<this.patNum&&(this.patNum=b)}this.patNum*=1E3;this.patNum=Math.round(this.patNum)/1E3};
Animator.prototype.draw=function(a){var b=this.actor,c=this.width,d=this.height,e=0,f=0;this.type&Animator.TYPE.X?e=c*Math.floor(this.patNum):this.type&Animator.TYPE.Y?f=d*Math.floor(this.patNum):this.type&Animator.TYPE.V&&(f=d*(parseInt(this.patNum)+(this.numY?parseInt(this.numY/2):0)));a.save();this.type==Animator.TYPE.NONE&&b.isInverse&&a.rotate(Math.PI);this.type&Animator.TYPE.ROTATION&&a.rotate(b.radian);b.scale&&a.scale(b.scale,b.scale);a.drawImage(this.img,e,f,c,d,-this.hW,-this.hH,c,d);a.restore()};
Animator.TYPE={NONE:0,ROTATION:1,X:2,Y:4,XY:6,H:8,V:16};function AudioMixer(){Repository.apply(this,arguments);this.type="arraybuffer";this.ctx=null;if(window.AudioContext||window.webkitAudioContext)this.ctx=new (window.AudioContext||window.webkitAudioContext);this.dic=[];this.bgm=[];this.lastTime=this.lastKey=null}AudioMixer.prototype=Object.create(Repository.prototype);AudioMixer.INSTANCE=new AudioMixer;
AudioMixer.prototype.makeName=function(a){var b=navigator.userAgent.toLowerCase();return-1!==b.indexOf("edge")||-1!==b.indexOf("safari")?"/audio/"+a+".mp3":"/audio/"+a+".webm"};AudioMixer.prototype.onload=function(a,b,c){var d=this;null===this.ctx?this.done():this.ctx.decodeAudioData(c,function(b){d.dic[a]=b;d.done()})};
AudioMixer.prototype.play=function(a){if(null!==this.ctx&&this.dic[a]){var b=arguments.length,c=1<b?arguments[1]:1,d=2<b?arguments[2]:!1,e=3<b?arguments[3]:0,b=4<b?arguments[4]:0,f=this.dic[a],g=new AudioElement(this.ctx,f,b);d&&(g.source.loopEnd=f.duration-.05,g.source.loop=!0,this.bgm.push(g),this.lastKey=a);g.gainNode.gain.value=c;g.setPan(e);this.lastTime=this.ctx.currentTime-b}};AudioMixer.prototype.setPan=function(a){this.bgm.forEach(function(b){b.setPan(a)})};AudioMixer.prototype.fade=function(){this.bgm.forEach(function(a){a.fade()})};
AudioMixer.prototype.stop=function(){this.bgm.forEach(function(a){a.stop()})};AudioMixer.prototype.getCurrentTime=function(){if(0<this.bgm.length){var a=[];this.bgm.forEach(function(b){b.done||a.push(b)});this.bgm=a}return this.bgm.length?this.ctx.currentTime-this.lastTime:null};AudioMixer.prototype.setCurrentTime=function(a){this.bgm.length&&(this.stop(),this.play(this.lastKey,1,!0,0,a))};
function AudioElement(a,b,c){var d=this;this.done=!1;this.source=a.createBufferSource();this.gainNode=a.createGain();this.gainNode.connect(a.destination);"function"==typeof a.createStereoPanner?(this.panNode=a.createStereoPanner(),this.panNode.connect(this.gainNode),this.source.connect(this.panNode)):(this.panNode=null,this.source.connect(this.gainNode));this.source.buffer=b;this.source.start(0,c);this.source.onended=function(){d.done=!0}}
AudioElement.prototype.setPan=function(a){this.panNode&&(this.panNode.pan.value=a)};AudioElement.prototype.fade=function(){var a=this,b=this.gainNode.gain,c=b.value,d=function(){0==Math.floor(100*c)?a.stop():(c*=.9,b.value=c,setTimeout(d,600))};d()};AudioElement.prototype.stop=function(){this.done||this.source.stop()};var Bullet=function(a,b){Actor.call(this,a,b);this.region=new Region(this,2);this.speed=2;this.width=4;this.fillStyle="rgba(120, 200, 255, 0.7)";this.recalculation()};
$jscomp.inherits(Bullet,Actor);Bullet.DEG_STEP=Actor.DEG_STEP;Bullet.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Bullet.prototype.move=function(a){Actor.prototype.move.call(this,a);this.walled&&this.eject()};var Capsule=function(a){Actor.call(this,a.x,a.y,-1);this.region=new Region(this,8);this.speed=0};$jscomp.inherits(Capsule,Actor);Capsule.DEG_STEP=Actor.DEG_STEP;Capsule.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Capsule.prototype.move=function(a){Actor.prototype.move.call(this,a);this.region.isHit(a.region)&&this.fate(a)};
Capsule.RANGE=20;var Chamber=function(a,b,c,d){c=void 0===c?Number.MAX_SAFE_INTEGER:c;d=void 0===d?{}:d;this.type=a;this.cycle=b;this.max=c;this.opt=d;this.reset()};Chamber.prototype.reset=function(){this.tick=0;this.hands=[]};Chamber.prototype.probe=function(){var a=[];this.hands.forEach(function(b){b.isGone||a.push(b)});this.hands=a;this.tick++};
Chamber.prototype.fire=function(a,b){b=void 0===b?null:b;if(this.tick<this.cycle||this.max<=this.hands.length)return null;var c=new this.type(a.x,a.y,this.opt);if(b){var d=a.calcDistance(b),e=Field.Instance.stage.getFg();c.dir=Math.atan2(b.y-a.y,b.x-a.x+d/c.speed*e.speed)}this.tick=0;this.hands.push(c);return c};var Controller=function(a){this.keys={};this.point={};this.touch=!1;this.init(void 0===a?!1:a);Controller.Instance=this};
Controller.prototype.init=function(a){a||window.addEventListener("contextmenu",function(a){a.preventDefault()});this.initKeys();this.initPointingDevice()};Controller.prototype.initKeys=function(){var a=this;window.addEventListener("keydown",function(b){b.key?a.keys[b.key]=!0:a.keys["k"+b.keyCode]=!0});window.addEventListener("keyup",function(b){b.key?delete a.keys[b.key]:delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this,b=document.getElementById("canvas"),c=function(){a.touch=!1;a.point=null};b.addEventListener("mousedown",function(b){a.touch=!0;a.point=FlexibleView.Instance.convert(b.clientX,b.clientY)});b.addEventListener("mousemove",function(b){a.touch&&(a.point=FlexibleView.Instance.convert(b.clientX,b.clientY))});b.addEventListener("mouseup",function(){return c()});b.addEventListener("mouseleave",function(){return c()});b.addEventListener("touchstart",
function(b){var c=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(c.pageX,c.pageY);b.preventDefault()});b.addEventListener("touchmove",function(b){b=b.touches[0];a.touch=!0;a.point=FlexibleView.Instance.convert(b.pageX,b.pageY)});b.addEventListener("touchend",function(){return c()})};var Enemy=function(a,b,c){Actor.call(this,a,b,void 0===c?0:c);this.radian=Math.PI;this.routine=null;this.routineCnt=this.routineIx=0;this.chamberList=[new Chamber(Bullet,Enemy.TRIGGER_CYCLE)]};
$jscomp.inherits(Enemy,Actor);Enemy.DEG_STEP=Actor.DEG_STEP;Enemy.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Enemy.prototype.move=function(a){this.routine&&this.routine[this.routineIx].tick(this,a);var b=Actor.prototype.move.call(this,a);!(a instanceof Enemy)&&this.calcDistance(a)<Enemy.TRIGGER_ALLOWANCE&&(b=[]);return b};Enemy.TRIGGER_CYCLE=50;Enemy.TRIGGER_ALLOWANCE=100;Enemy.MAX_TYPE=127;Enemy.LIST=[];Enemy.assign=function(a,b,c){a=Object.assign({},Enemy.LIST[a%Enemy.LIST.length]);a.x=b;a.y=c;return a};
var Chain=function(a,b){Enemy.call(this,a,b);this.next=this.prev=null};$jscomp.inherits(Chain,Enemy);Chain.DEG_STEP=Enemy.DEG_STEP;Chain.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Chain.assign=Enemy.assign;Chain.LIST=Enemy.LIST;Chain.MAX_TYPE=Enemy.MAX_TYPE;Chain.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Chain.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Chain.prototype.unshift=function(a){a.next=this;if(a.prev=this.prev)this.prev.next=a;this.prev=a;return this};
Chain.prototype.push=function(a){a.prev=this;if(a.next=this.next)this.next.prev=a;this.next=a;return this};Chain.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;return this.next};
var Field=function(a,b){Matter.call(this,0,0);this.view=new FlexibleView(a,b);this.width=a;this.height=b;this.ship=new Ship(-100,100);this.ship.isGone=!0;this.shipRemain=0;this.actorList=[];this.enemyCycle=this.hiscore=this.score=0;this.stage=Stage.LIST[0];this.stageNum=0;this.landform=new Landform(this.view.canvas);Field.Instance=this};$jscomp.inherits(Field,Matter);
Field.prototype.nextStage=function(){var a=Stage.LIST[this.stageNum];this.stage=a;this.landform.loadStage(a);this.stageNum++;Stage.LIST.length<=this.stageNum&&(this.stageNum=0)};Field.prototype._reset=function(){this.phase=Field.PHASE.NORMAL;this.ship.reset();this.ship.x=100;this.ship.y=100;this.ship.enter();this.actorList=[this.ship];this.hibernate=Field.MAX_HIBERNATE};Field.prototype.reset=function(){this.landform.reset();this._reset()};Field.prototype.retry=function(){this.landform.retry();this._reset()};
Field.prototype.startGame=function(){this.loosingRate=Field.MAX_LOOSING_RATE;this.score=0;this.shipRemain=Field.MAX_SHIP;this.stageNum=0;this.nextStage();this._reset()};Field.prototype.endGame=function(){document.getElementById("gameOver").classList.remove("hidden")};Field.prototype.isGameOver=function(){return!document.getElementById("gameOver").classList.contains("hidden")};Field.prototype.calcPan=function(a){return(a-this.hW)/this.hW};
Field.prototype.move=function(){var a=this;if(this.phase!=Field.PHASE.BOSS){this.landform.scanEnemy().forEach(function(b){b=b.formation?(new Formation(b.x,b.y)).setup(b.type,8):new b.type(b.x,b.y);a.actorList.push(b)});var b=this.landform.forward(this.ship);this.isGameOver()||(b==Landform.NEXT.NOTICE?(AudioMixer.INSTANCE.fade(),this.stage.notice()):b==Landform.NEXT.ARRIV?(this.phase=Field.PHASE.BOSS,this.stage.toBossMode()):b==Landform.NEXT.PAST&&this.nextStage(),Field.MIN_LOOSING_RATE<this.loosingRate&&
(this.loosingRate-=this.loosingRate/1E4))}};
Field.prototype.draw=function(){var a=this,b=this.ctx,c=this.ship,d=[],e=[],f=[],g=0;this.view.clear();this.landform.drawBg(b);this.actorList.sort(function(a,b){return a.z-b.z});this.actorList.forEach(function(h){if(!h.isGone){h instanceof Bullet?h.isHit(c):h instanceof Enemy?(h.triggered=0==parseInt(Math.random()*a.loosingRate/10),h.isHit(c),e.push(h)):(h instanceof Shot||h instanceof Missile)&&d.push(h);var k=h.move(c);k instanceof Array&&k.forEach(function(a){f.push(a)});a.landform.effect(h);a.landform.hitTest(h);
h.draw(b);f.push(h);h.explosion&&h.score&&(g+=h.score,h.score=0)}});d.forEach(function(a){e.forEach(function(b){return b.isHit(a)})});this.phase==Field.PHASE.BOSS&&0==e.length&&(this.phase=Field.PHASE.NORMAL,AudioMixer.INSTANCE.fade());this.actorList=f;this.landform.draw();this.score+=g;this.showScore();!this.isGameOver()&&c.isGone&&(AudioMixer.INSTANCE.stop(),0<--this.hibernate||(0<--this.shipRemain?this.retry():this.endGame()))};
Field.prototype.showScore=function(){this.hiscore<this.score&&(this.hiscore=this.score);var a=document.querySelector("#score > div > div:nth-child(2)"),b=document.querySelector("#score > div:nth-child(2) > div:nth-child(2)");document.querySelector("#score > div:nth-child(3)");var c=document.querySelector("#remain > div > div:nth-child(1)");a&&(a.innerHTML=this.score,b.innerHTML=this.hiscore,this.shipRemain&&(c.style.width=16*(this.shipRemain-1)+"px"))};
$jscomp.global.Object.defineProperties(Field.prototype,{ctx:{configurable:!0,enumerable:!0,get:function(){return this.view.ctx}}});Field.MAX_ENEMIES=100;Field.ENEMY_CYCLE=10;Field.MIN_LOOSING_RATE=1;Field.MAX_LOOSING_RATE=2E4;Field.MAX_SHIP=7;Field.MAX_HIBERNATE=5*Actor.MAX_EXPLOSION;Field.PHASE={NORMAL:0,BOSS:1};
var FlexibleView=function(a,b){this.view=document.getElementById("view");this.canvas=document.getElementById("canvas");this.ctx=this.canvas.getContext("2d");this.scale=1;this.init();this.setSize(a,b);FlexibleView.Instance=this};FlexibleView.prototype.setSize=function(a,b){this.width=a;this.height=b;this.canvas.width=a;this.canvas.height=b;this.resize()};
FlexibleView.prototype.init=function(){var a=this,b=document.querySelector('[data-role="header"]'),c=document.querySelector('[data-role="footer"]');this.headerHeight=b?b.offsetHeight:0;this.footerHeight=c?c.offsetHeight:0;this.margin=this.headerHeight+this.footerHeight;window.addEventListener("resize",function(){a.resize()});window.addEventListener("keydown",function(){view.classList.contains("addicting")||view.classList.add("addicting")});window.addEventListener("mousemove",function(){view.classList.remove("addicting")})};
FlexibleView.prototype.resize=function(){var a=document.body.clientWidth/this.width,b=(window.innerHeight-this.margin)/this.height;this.scale=b<a?b:a;this.view.setAttribute("style",["width:"+this.width+"px","height:"+this.height+"px","transform: scale("+this.scale+")"].join(";"))};FlexibleView.prototype.convert=function(a,b){return{x:a/this.scale,y:(b-this.headerHeight)/this.scale}};FlexibleView.prototype.clear=function(){this.ctx.clearRect(0,0,this.width,this.height)};
var Formation=function(a,b){Actor.call(this,a,b);this.effectH=!1;this.count=this.steps=0;this.enemies=[]};$jscomp.inherits(Formation,Actor);Formation.DEG_STEP=Actor.DEG_STEP;Formation.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Formation.prototype.setup=function(a,b){for(var c=0;c<b;c++){var d=new a(this.x,this.y);this.bonus||(this.bonus=this.score=10*d.score);this.enemies.push(d)}return this};
Formation.prototype.isDestroyed=function(){var a=this,b=[];this.enemies.forEach(function(c){0!=c.hitPoint&&(b.push(c),a.x=c.x,a.y=c.y)});this.enemies=b;return 0==b.length&&0==this.explosion?(this.explosion=4*Actor.MAX_EXPLOSION,!0):!1};Formation.prototype.move=function(a){Actor.prototype.move.call(this,a);if(this.enemies.length<=this.count){if(this.isDestroyed())return a=[SpeedupCapsule,MissileCapsule],[new (a[Math.floor(Math.random()*a.length)])(this)]}else if(0==this.steps++%Formation.STEP)return[this.enemies[this.count++]]};
Formation.prototype.drawExplosion=function(a){a.fillStyle="rgba(240, 240, 255, .8)";a.fillText(this.bonus,0,0)};Formation.STEP=10;var ImageManager=function(){this.loaded=this.max=0;this.dic={}};ImageManager.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};
ImageManager.prototype.reserve=function(a){for(var b=[],c=0;c<arguments.length;++c)b[c-0]=arguments[c];var d=this;b.forEach(function(a){if(!(a in d.dic)){var b=new Image;b.onload=function(){d.dic[a]=b;d.loaded++};b.src=36==a.length?"/image/src?id="+a:"/img/"+a;d.max++}})};ImageManager.Instance=new ImageManager;
var Landform=function(a,b){b=void 0===b?!1:b;var c=this;this.canvas=a;this.ctx=a.getContext("2d");this.isEdit=b;this.effectH=0;this.next=Landform.NEXT.NONE;this.col=0;this.magni=this.colDir=1;this.target=null;this.ty=this.tx=0;this.selection="b0";this.lastScan=this.brickVal=this.brick=this.which=null;this.touch=!1;this.img=new Image;this.img.onload=function(){var a=Field.Instance;c.width=c.img.width;c.height=c.img.height;c.bw=c.img.width/Landform.BRICK_WIDTH;c.bh=c.img.height/Landform.BRICK_WIDTH;
a&&(c.viewX=c.img.width-1.5*a.hW,c.arrivX=c.img.width-a.width,c.noticeX=c.arrivX-a.hW)};this.reverse=new Image;this.reverse.src="/img/reverse.png";this.touch=!1};Landform.BRICK_WIDTH=8;Landform.BRICK_HALF=Landform.BRICK_WIDTH/2;Landform.BRICK_TYPE={WALL:255,BRITTLE:254};Landform.COL_MAX=512;Landform.NEXT={NONE:0,NOTICE:1,ARRIV:2,IDLE:3,PAST:4};Landform.prototype.load=function(a){a instanceof File&&(this.img.src=window.URL.createObjectURL(a))};
Landform.prototype.loadMapData=function(a){var b=this,c=new Image;c.onload=function(){var a=document.createElement("canvas"),e=a.getContext("2d");a.width=this.width;a.height=this.height;e.drawImage(c,0,0);b.brick=e.getImageData(0,0,this.width,this.height);b.touch=!0};c.src=a instanceof File?window.URL.createObjectURL(a):a};Landform.prototype.loadStage=function(a){var b=a.getFg();this.stage=a;this.loadMapData("/img/"+a.map);this.img.src=b.img.src;this.reset()};
Landform.prototype.reset=function(){this.next=Landform.NEXT.NONE;this.stage&&this.stage.reset()};Landform.prototype.retry=function(){this.next=Landform.NEXT.NONE;this.stage&&(this.stage.retry(),this.loadMapData("./img/"+this.stage.map))};
Landform.prototype.effect=function(a){var b=Math.max(Field.Instance.width+a.width,a.maxX);a.effectH&&(a.x-=this.effectH);if(a.effectV&&this.next==Landform.NEXT.NONE){var c=this.stage.getFg().speed;a.y+=this.stage.effectV*c}(a.x<a.minX||b<a.x)&&a.eject();this.stage.scroll==Stage.SCROLL.OFF?(a.y<a.minY||a.maxY<a.y)&&a.eject():this.stage.scroll==Stage.SCROLL.ON?(a.y<-this.height||this.height+a.maxY<a.y)&&a.eject():a.gravity&&Landform.BRICK_WIDTH+Landform.BRICK_HALF<Math.abs(a.dy*a.speed)?a.eject():0>
a.y?a.y+=this.height:this.height<a.y&&(a.y-=this.height)};
Landform.prototype.forward=function(a){if(!this.width)return Landform.NEXT.NONE;var b=this.stage.getFg();this.next!=Landform.NEXT.ARRIV&&this.stage.scrollV(a);if(this.viewX<=b.x)return this.effectH=0,this.next!=Landform.NEXT.PAST?this.next=Landform.NEXT.PAST:Landform.NEXT.NONE;this.stage.forward();this.effectH=b.effectH;if(this.arrivX<=b.x){if(this.next==Landform.NEXT.NOTICE)return b.x=this.arrivX,this.effectH=0,this.next=Landform.NEXT.ARRIV;if(this.arrivX<b.x)return this.next=Landform.NEXT.IDLE}else if(this.noticeX<=
b.x&&this.next!=Landform.NEXT.NOTICE)return this.next=Landform.NEXT.NOTICE;return Landform.NEXT.NONE};
Landform.prototype.scanEnemy=function(){var a=[];if(!this.brick||this.next==Landform.NEXT.IDLE)return a;var b=Field.Instance,c=this.stage.getFg(),d=c.x,c=c.y,e=Math.round((d+b.width-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(0>e||e===this.lastScan)return a;this.lastScan=e;for(var b=b.width+Landform.BRICK_WIDTH,f=0;f<this.bh;f++){var g=this.brick.data[f*this.bw*4+4*e+1];0<g&&g<=Enemy.MAX_TYPE&&a.push(Enemy.assign(g-1,b,-c+(f+1)*Landform.BRICK_WIDTH))}e=Math.round(d/Landform.BRICK_WIDTH);if(0>e)return a;
for(d=0;d<this.bh;d++)b=this.brick.data[d*this.bw*4+4*e+1],Enemy.MAX_TYPE<b&&a.push(Enemy.assign(b-1-Enemy.MAX_TYPE,0,-c+(d+1)*Landform.BRICK_WIDTH));return a};Landform.prototype.hitTest=function(a){this.brick&&(a.walled=this.getBrick(a,2),this.target=a)};Landform.prototype.smashWall=function(a){this.stage.getFg().smashWall(a);this.putBrick(a,2,0)};
Landform.prototype.scanFloor=function(a){if(this.brick){var b,c=this.getBrick(a,2),d=0>a.gravity?-1:1;if(0<c){for(b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;0<c;)b-=Landform.BRICK_WIDTH*d,c=this.getBrick({x:a.x,y:b},2);b+=Landform.BRICK_WIDTH*d}else if(b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,0>d){for(;0<b&&!c;)b-=Landform.BRICK_WIDTH,c=this.getBrick({x:a.x,y:b},2);c||(b=-a.height-Landform.BRICK_WIDTH)}else{for(;b<this.height&&!c;)b+=Landform.BRICK_WIDTH,c=this.getBrick({x:a.x,
y:b},2);c||(b=this.height+a.height+Landform.BRICK_WIDTH)}return b}};Landform.prototype.getHorizontalAngle=function(a){var b={x:a.x+Landform.BRICK_WIDTH,y:a.y-2*Landform.BRICK_WIDTH},c=this.scanFloor({x:a.x-Landform.BRICK_WIDTH,y:a.y-2*Landform.BRICK_WIDTH}),b=this.scanFloor(b);return Math.atan2(b-c,a.width)};
Landform.prototype.getBrickIndex=function(a){var b=this.stage.getFg(),c=Math.round((b.x+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(0>c||this.bw<c)return-1;a=Math.round((b.y+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);a%=this.bh;return a*this.bw*4+4*c};Landform.prototype.getBrick=function(a,b){if(!this.brick)return null;a=this.getBrickIndex(a);return 0>a?null:this.brick.data[a+b]};
Landform.prototype.wheel=function(a){var b=this.stage.getFg();0>a?(b.y+=2*Landform.BRICK_WIDTH,this.height<=b.y&&(b.y=0)):(0==b.y&&(b.y=this.height),b.y-=2*Landform.BRICK_WIDTH)};Landform.prototype.putBrick=function(a,b,c){a=this.getBrickIndex(a);0>a||(this.brick.data[a+b]=c,this.brick.data[a+3]=c?255:0)};
Landform.prototype.drawEnemy=function(a,b,c){var d=Enemy.MAX_TYPE<a;a=Enemy.LIST[(d?a-Enemy.MAX_TYPE:a)-1];var e=a.formation?3:1,f=a.instance,g=this.ctx;if(!a.instance)return null;f.x=b+f.hW;for(f.y=c+f.hH;e--;)f.draw(g),f.x+=2,f.y+=2;d&&(g.save(),g.translate(f.x,f.y),g.drawImage(this.reverse,-8,-4),g.restore());return f};
Landform.prototype.drawTarget=function(){if(this.isEdit&&this.target){var a=Math.round((this.target.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,b=Math.round((this.target.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,c=this.ctx,d=Landform.BRICK_WIDTH,e=parseInt(this.selection);0<e&&(e=this.drawEnemy(e,a,b))&&(d=e.width);c.save();c.fillStyle="rgba(128, 255, 255, .4)";c.fillRect(a,b,d,d);c.restore();this.touchDown(a,b)}};
Landform.prototype.touchDown=function(a,b){if(!this.which)this.ty=this.tx=-1,this.brickVal=null;else if(this.tx!=a||this.ty!=b){var c=parseInt(this.selection);if(0<c){var d=this.getBrick(this.target,1),e=d-Enemy.MAX_TYPE;!d||d!=c&&e!=c?this.putBrick(this.target,1,c):d==c?this.putBrick(this.target,1,c+Enemy.MAX_TYPE):this.putBrick(this.target,1,0)}else d=this.getBrick(this.target,2),c=this.selection.substr(1),null==this.brickVal&&(this.brickVal=0<d?0:255-c),this.putBrick(this.target,2,this.brickVal);
this.touch=!0;this.tx=a;this.ty=b}};
Landform.prototype.drawBrick=function(){if(this.brick&&this.isEdit){var a=Field.Instance,b=this.stage.getFg(),c=b.x,d=b.y,b=this.ctx,e=255<this.col?this.col-256:0,f=255<this.col?255:this.col%256,g=Landform.BRICK_WIDTH-2,h=Math.round(c/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH,k=h/Landform.BRICK_WIDTH,l=Math.min(k+512/Landform.BRICK_WIDTH,this.bw),n=Math.round(d/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH/Landform.BRICK_WIDTH,r=this.brick.data;b.save();b.translate(-c,-d);b.strokeStyle="rgba("+e+", "+
f+", 255, .4)";b.fillStyle=b.strokeStyle;for(d=0;d<this.bh;d++)for(var f=n+d,e=f*Landform.BRICK_WIDTH,f=4*(f%this.bh*this.bw+k),q=k,p=h;q<l;q++,p+=Landform.BRICK_WIDTH,f+=4)if(!(0>q)){var m=r[f+1];m&&this.drawEnemy(m,p,e);m=r[f+2];if(255==m)b.fillRect(p,e,g,g);else if(254==m){var m=p+Landform.BRICK_HALF-1,t=e+Landform.BRICK_HALF-1;b.beginPath();b.arc(m,t,g/2,0,Math.PI2,!1);b.stroke();b.strokeRect(p,e,g,g)}}this.width-a.width<=c&&(a=this.width-Landform.BRICK_WIDTH,b.fillStyle="rgba(255, 0, 0, .4)",
b.fillRect(a,0,Landform.BRICK_WIDTH,this.height));b.restore();this.col+=16*this.colDir;if(0>=this.col||Landform.COL_MAX<=this.col)this.colDir*=-1}};Landform.prototype.drawBg=function(a){this.stage&&(a.save(),a.scale(this.magni,this.magni),this.stage.drawBg(a),a.restore())};
Landform.prototype.draw=function(){if(this.stage){var a=this.ctx;a.save();a.scale(this.magni,this.magni);this.stage.drawFg(a);this.drawBrick();this.drawTarget();a.restore();this.brick&&this.isEdit&&this.touch&&this.brick&&(this.updateMap(),this.touch=!1)}};
Landform.prototype.updateMap=function(){var a=document.getElementById("mapImage");if(a){var b=document.createElement("canvas"),c=b.getContext("2d");b.width=this.brick.width;b.height=this.brick.height;c.putImageData(this.brick,0,0);a.setAttribute("src",b.toDataURL("image/png"))}};Landform.prototype.getImageData=function(){var a=document.createElement("canvas"),b=a.getContext("2d");a.width=this.width;a.height=this.height;b.drawImage(this.img,0,0);return b.getImageData(0,0,this.width,this.height)};
Landform.prototype.getBrickData=function(a){return null!=this.brick?this.brick:a.createImageData(this.width/Landform.BRICK_WIDTH,this.height/Landform.BRICK_WIDTH)};
Landform.prototype.generateBrick=function(a){if(this.img.src&&this.img.complete){var b=this.getImageData(),c=this.width/Landform.BRICK_WIDTH,d=this.height/Landform.BRICK_WIDTH;a=this.getBrickData(a);var e=a.data,f=this.width*Landform.BRICK_HALF+4*Landform.BRICK_HALF,g=0;console.log(this.width+" x "+this.height+" | "+this.width*this.height*4);console.log(c+" x "+d+" | "+e.length);for(var h=0;h<d;h++){for(var k=0;k<c;k++){for(var l=!1,n=0;4>n;n++)b.data[f+n]&&(l=!0);l=l?255:0;e[g+2]=l;e[g+3]=l;f+=4*
Landform.BRICK_WIDTH;g+=4}f+=this.width*(Landform.BRICK_WIDTH-1)*4}console.log("ix:"+g);console.log("sx:"+f);this.brick=a;this.touch=!0}};Math.PI2=Math.PI2||2*Math.PI;Math.SQ=Math.SQ||Math.PI/2;Math.trim=Math.trim||function(a){for(;Math.PI<a;)a-=Math.PI2;for(;a<-Math.PI;)a+=Math.PI2;return a};Math.close=Math.close||function(a,b,c){b=Math.trim(a-b);return Math.abs(b)<=c?a:0<b?a-c:a+c};function Matrix(a){this.mat=a}Matrix.NO_EFFECT=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]];
Matrix.rotateX=function(a){return new Matrix([[1,0,0,0],[0,Math.cos(a),-Math.sin(a),0],[0,Math.sin(a),Math.cos(a),0],[0,0,0,1]])};Matrix.rotateY=function(a){return new Matrix([[Math.cos(a),0,Math.sin(a),0],[0,1,0,0],[-Math.sin(a),0,Math.cos(a),0],[0,0,0,1]])};Matrix.rotateZ=function(a){return new Matrix([[Math.cos(a),-Math.sin(a),0,0],[Math.sin(a),Math.cos(a),0,0],[0,0,1,0],[0,0,0,1]])};
Matrix.prototype.multiply=function(a){var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]],c=a.mat;this.mat.forEach(function(a,e){a.forEach(function(d,g){for(var f=d=0;4>f;f++)d+=a[f]*c[f][g];b[e][g]=d})});return new Matrix(b)};Matrix.prototype.affine=function(a,b,c){var d=this.mat;return{x:d[0][0]*a+d[0][1]*b+d[0][2]*c+d[0][3],y:d[1][0]*a+d[1][1]*b+d[1][2]*c+d[1][3],z:d[2][0]*a+d[2][1]*b+d[2][2]*c+d[2][3]}};
var Missile=function(a,b,c){Actor.call(this,a,b);this.dir=c.dir;this.speed=3;this.width=2.5;this.gravity=c.gravity;this.recalculation();this.shuttle=3;this.fillStyle="rgba(200, 200, 255, 0.6)"};$jscomp.inherits(Missile,Actor);Missile.DEG_STEP=Actor.DEG_STEP;Missile.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Missile.prototype.reactX=function(a){Actor.prototype.reactX.call(this,a);this.shuttle--;0>this.shuttle&&this.fate()};Missile.prototype.fate=function(){this.eject()};
function Gizmo(a,b,c){this.type=a;this.destination=b;this.param=void 0===c?null:c}Gizmo.TYPE={FIXED:0,OWN:1,AIM:2,CHASE:3};Gizmo.DEST={TO:0,TO_X:1,TO_Y:2,ROTATE:3,ROTATE_L:4,ROTATE_R:5,LEFT:6,RIGHT:7};
Gizmo.prototype.tick=function(a,b){if(this.type==Gizmo.TYPE.FIXED)this.destination==Gizmo.DEST.ROTATE?a.radian=a.dir:a.dir=null;else if(this.type==Gizmo.TYPE.OWN)this.destination==Gizmo.DEST.ROTATE_L?a.dir-=a.step:this.destination==Gizmo.DEST.ROTATE_R?a.dir+=a.step:this.destination==Gizmo.DEST.LEFT?a.dir=Math.PI:this.destination==Gizmo.DEST.RIGHT&&(a.dir=0);else{var c=b.x-a.x,d=b.y-a.y;Math.abs(c)<=a.speed&&(c=0);Math.abs(d)<=a.speed&&(d=0);this.type==Gizmo.TYPE.AIM?this.destination==Gizmo.DEST.TO_X?
a.radian=0>c?Math.PI:0:this.destination==Gizmo.DEST.TO_Y?a.radian=0>c?-Math.SQ:Math.SQ:this.destination==Gizmo.DEST.ROTATE&&(b=a.calcDistance(b),a.speed<b&&(a.radian=Math.close(a.radian,Math.atan2(d,c),this.param?this.param:Math.PI/30),a.radian=Math.trim(a.radian))):this.type==Gizmo.TYPE.CHASE&&(this.destination==Gizmo.DEST.TO?a.dir=Math.atan2(d,c):this.destination==Gizmo.DEST.TO_X&&c?a.dir=Math.atan2(0,c):this.destination==Gizmo.DEST.TO_Y&&d?a.dir=Math.atan2(d,0):this.destination==Gizmo.DEST.ROTATE&&
(a.dir=Math.close(a.dir,Math.atan2(d,c),this.param?this.param:Math.PI/60),a.radian=a.dir))}};function Movement(a){var b=parseInt(a);this.cond=a;this.count=b==a?b:null;this.list=[]}Movement.COND={X:"x",Y:"y"};Movement.prototype.add=function(a,b,c){this.list.push(new Gizmo(a,b,c));return this};
Movement.prototype.isValid=function(a,b){if(this.cond){if(this.count){if(a.routineCnt++<this.count)return!0;a.routineCnt=0;return!1}var c=b.x-a.x;b=b.y-a.y;return this.cond==Movement.COND.X&&Math.abs(c)<=a.speed||this.cond==Movement.COND.Y&&Math.abs(b)<=a.speed?!1:!0}};Movement.prototype.tick=function(a,b){this.list.forEach(function(c){c.tick(a,b)});this.isValid(a,b)||(a.routineIx++,a.routine.length<=a.routineIx&&(a.routineIx=0))};
var Region=function(a,b,c){b=void 0===b?Region.DefaultSize:b;c=void 0===c?Region.Type.CIRCLE:c;this.matter=a;this.size=b;this.type=c;this.width=2*b};Region.prototype.isHit=function(a){if(this.type==Region.Type.CIRCLE&&a.type==Region.Type.CIRCLE){var b=this.matter.x-a.matter.x,c=this.matter.y-a.matter.y;return Math.sqrt(b*b+c*c)<this.size+a.size}console.log("*Not implement*")};
Region.prototype.draw=function(a){a.save();a.strokeStyle="rgba(80, 255, 80, 0.6)";this.type==Region.Type.RECTANGLE?a.strokeRect(-this.size,-this.size,this.width,this.width):(a.beginPath(),a.arc(0,0,this.size,0,Math.PI2,!1),a.stroke());a.restore()};Region.DefaultSize=4;Region.Type={CIRCLE:1,RECTANGLE:2};function Repository(){this.loaded=this.max=0;this.dic={};this.reserved={};this.type="json"}Repository.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};
Repository.prototype.reserve=function(a){var b=this;a.forEach(function(a){null==a||a in b.reserved||(b.reserved[a]=!0,b.load(a))})};Repository.prototype.makeName=function(a){return a};Repository.prototype.load=function(a){var b=this,c=new XMLHttpRequest,d=this.makeName(a);this.max++;c.open("GET",d,!0);c.responseType=this.type;c.addEventListener("loadend",function(){var e=c.response;b.dic[a]=e;b.onload(a,d,e)});c.send()};Repository.prototype.onload=function(a,b,c){this.done()};
Repository.prototype.done=function(){this.loaded++};var Ship=function(a,b){Actor.call(this,a,b);this.effectH=!1;this.anim=new Animator(this,"ship001.png",Animator.TYPE.V,1,2*Ship.PATTERNS+1);this.reset()};$jscomp.inherits(Ship,Actor);Ship.DEG_STEP=Actor.DEG_STEP;Ship.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Ship.prototype.recalculation=function(){var a=Field.Instance;Actor.prototype.recalculation.call(this);a&&(this.right=a.width-2*this.width,this.bottom=a.height-this.hH)};
Ship.prototype.reset=function(){this.speed=Ship.MIN_SPEED;this.triggered=!1;this.chamberList=[new Chamber(Shot,4,Ship.MAX_SHOTS)];this.chamberList.forEach(function(a){return a.reset()});this.missileLevel=0};Ship.prototype.speedup=function(){this.speed*=1.25;Ship.MAX_SPEED<this.speed&&(this.speed=Ship.MAX_SPEED)};
Ship.prototype.powerUpMissile=function(){this.missileLevel++;1==this.missileLevel?this.chamberList.push(new Chamber(Missile,16,2,{gravity:.05,dir:0})):2==this.missileLevel?this.chamberList.push(new Chamber(Missile,16,2,{gravity:-.05,dir:0})):3==this.missileLevel&&(this.chamberList.push(new Chamber(Missile,16,2,{gravity:.05,dir:Math.PI})),this.chamberList.push(new Chamber(Missile,16,2,{gravity:-.05,dir:Math.PI})))};
Ship.prototype.inkey=function(a){var b=!1,c=0;if(a.ArrowLeft||a.Left||a.k37)c=1,b=!0;else if(a.ArrowRight||a.Right||a.k39)c=-1,b=!0;if(a.ArrowUp||a.Up||a.k38)c=2-.5*c,b=!0;else if(a.ArrowDown||a.Down||a.k40)c*=.5,b=!0;b&&(this.dir=(c+1)*Math.SQ);if(a.Control||a.Shift||a.k16||a.k17)this.triggered=!0};
Ship.prototype.move=function(){this.dir=null;this.aim(Controller.Instance.point);this.inkey(Controller.Instance.keys);Controller.Instance.touch&&(this.triggered=!0);var a=Actor.prototype.move.call(this);if(!this.isGone)if(this.walled)this.fate();else{if(this.x<this.hW||this.right<this.x)this.x=this.svX;if(this.y<this.hH||this.bottom<this.y)this.y=this.svY;return a}};Ship.MIN_SPEED=1.5;Ship.MAX_SPEED=5;Ship.MAX_SHOTS=7;Ship.PATTERNS=2;
var Shot=function(a,b){Actor.call(this,a,b);this.dir=0;this.width=2;this.speed=6;this.size=2;this.maxX=Field.Instance.width;this.fillStyle="rgba(255, 255, 0, 0.7)";a=Field.Instance.calcPan(this.x);AudioMixer.INSTANCE.play("sfx-fire",.4,!1,a)};$jscomp.inherits(Shot,Actor);Shot.DEG_STEP=Actor.DEG_STEP;Shot.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Shot.prototype.fate=function(){this.eject()};
Shot.prototype.move=function(a){Actor.prototype.move.call(this,a);this.walled&&(this.walled==Landform.BRICK_TYPE.BRITTLE&&Field.Instance.landform.smashWall(this),this.fate())};var Stage=function(a,b,c){var d=this;this.scrollSv=this.scroll=a;this.map=b;this.view=c;this.boss=this.bgm=this.fg=null;this.checkPoint=0;this.view.forEach(function(a){a.stage=d});this.effectV=this.effectH=0};
Stage.prototype.setBgm=function(a,b){this.bgm=a;this.boss=void 0===b?null:b;AudioMixer.INSTANCE.reserve([this.bgm,this.boss]);return this};Stage.prototype.playBgm=function(){this.bgm&&AudioMixer.INSTANCE.play(this.bgm,.7,!0)};Stage.prototype.getFg=function(){if(this.fg)return this.fg;var a;this.view.forEach(function(b){b instanceof StageFg&&(a=b)});return this.fg=a};Stage.prototype.reset=function(){this.checkPoint=Stage.CHECK_POINT[0];this.retry()};
Stage.prototype.retry=function(){var a=this;this.scroll=this.scrollSv;this.effectV=this.effectH=0;this.view.forEach(function(b){b.reset(a.checkPoint)});this.playBgm()};
Stage.prototype.scrollV=function(a){this.effectV=0;if(this.scroll!=Stage.SCROLL.OFF){var b=Field.Instance,c=b.hH-a.y;a=this.getFg();if(this.scroll==Stage.SCROLL.TOP)c=5*a.speed;else if(this.scroll==Stage.SCROLL.BOTTOM)c=5*-a.speed;else if(Math.abs(c)<a.speed)return;var c=c/3,d=a.y-c,b=a.height-b.height;if(this.scroll!=Stage.SCROLL.ON||!(0>d||b<d))if(this.scroll==Stage.SCROLL.TOP&&0>d)this.scroll=Stage.SCROLL.OFF;else{if(this.scroll==Stage.SCROLL.BOTTOM&&(console.log("nextY:"+d+"/"+a.height),b<d)){this.scroll=
Stage.SCROLL.OFF;return}this.effectV=c}}};Stage.prototype.forward=function(a){var b=this;this.view.forEach(function(b){b.forward(a)});var c=this.getFg().x;Stage.CHECK_POINT.forEach(function(a){a<=c&&b.checkPoint<c&&(b.checkPoint=a)})};Stage.prototype.drawBg=function(a){this.view.forEach(function(b){b instanceof StageFg||b.draw(a)})};Stage.prototype.drawFg=function(a){this.view.forEach(function(b){b instanceof StageBg||b.draw(a)})};
Stage.prototype.notice=function(){if(this.scroll==Stage.SCROLL.ON||this.scroll==Stage.SCROLL.LOOP){var a=this.getFg();this.scroll=a.y<a.height/2?Stage.SCROLL.TOP:Stage.SCROLL.BOTTOM}};Stage.prototype.toBossMode=function(){this.boss&&AudioMixer.INSTANCE.play(this.boss,.7,!0)};Stage.SCROLL={OFF:0,ON:1,LOOP:2,TOP:4,BOTTOM:8};Stage.LIST=[];Stage.CHECK_POINT=[0,660,1440];
var StageView=function(a,b,c,d){this.imageId=a;this.speed=b;this.dir=c;this.blink=d;this.ready=!1;this.pattern=null;this.repeatY=this.repeatX=2;ImageManager.Instance.reserve(a)};StageView.prototype.reset=function(a){if(!this.width){var b=this.img;this.width=b.width;this.height=b.height;this.w2=b.width*this.repeatX;this.h2=b.height*this.repeatY}this.x=a%this.width;this.effectV=this.effectH=this.y=0;this.alpha=1;this.blinkDir=-1};
StageView.prototype.forward=function(){var a=this.stage.effectV;this.effectH=Math.cos(this.dir)*this.speed;this.effectV=Math.sin(this.dir)*this.speed;this.x+=this.effectH;this.y+=this.effectV;this.y-=a*this.speed;this.width<this.x&&(this.x-=this.width);0>this.y&&(this.y+=this.height);this.height<this.y&&(this.y-=this.height);this.blink&&(this.alpha+=this.blinkDir*this.blink,.3>=this.alpha||1<=this.alpha)&&(this.blinkDir*=-1)};
StageView.prototype.getPattern=function(a){this.pattern||(this.pattern=a.createPattern(this.img,"repeat"));return this.pattern};StageView.prototype.draw=function(a){a.save();a.globalAlpha=this.alpha;a.translate(-this.x,-this.y);a.beginPath();a.fillStyle=this.getPattern(a);a.rect(0,0,this.w2,this.h2);a.fill();a.restore()};$jscomp.global.Object.defineProperties(StageView.prototype,{img:{configurable:!0,enumerable:!0,get:function(){return ImageManager.Instance.dic[this.imageId]}}});
var StageFg=function(a,b,c,d){StageView.call(this,a,void 0===b?.5:b,void 0===c?0:c,void 0===d?0:d);this.repeatX=1};$jscomp.inherits(StageFg,StageView);StageFg.prototype.createCanvas=function(){var a=document.createElement("canvas"),b=a.getContext("2d");a.width=this.width;a.height=this.height;b.clearRect(0,0,this.width,this.height);b.drawImage(this.img,0,0);return a};
StageFg.prototype.reset=function(a){StageView.prototype.reset.call(this,a);0==a&&(this.x=-Field.Instance.width);this.ready&&(this.canvas=this.createCanvas(),this.pattern=canvas.getContext("2d").createPattern(this.canvas,"repeat"))};
StageFg.prototype.smashWall=function(a){var b=Math.round((this.x+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;a=Math.round((this.y+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var c=this.canvas.getContext("2d");a%=this.height;c.clearRect(b,a,Landform.BRICK_WIDTH,Landform.BRICK_WIDTH);this.pattern=c.createPattern(this.canvas,"repeat")};var StageBg=function(a,b,c,d){StageView.call(this,a,void 0===b?.5:b,void 0===c?0:c,void 0===d?0:d)};
$jscomp.inherits(StageBg,StageView);var EntityBase=function(a){this.base=a};EntityBase.prototype.list=function(a){a=void 0===a?{}:a;return $.ajax({type:"post",url:"/"+this.base+"/list",dataType:"json",data:a})};EntityBase.prototype.select=function(a){var b=new FormData;b.append("id",a);return fetch("/"+this.base+"/select",{method:"post",body:b}).then(function(a){return a.json()})};
EntityBase.prototype.save=function(a){return $.ajax({type:"post",url:"/"+this.base+"/save",dataType:"json",data:a,processData:!1,contentType:!1})};var ActorEntity=function(){EntityBase.call(this,"actor")};$jscomp.inherits(ActorEntity,EntityBase);var AudioEntity=function(){EntityBase.call(this,"audio")};$jscomp.inherits(AudioEntity,EntityBase);var ImageEntity=function(){EntityBase.call(this,"image")};$jscomp.inherits(ImageEntity,EntityBase);var ProductEntity=function(){EntityBase.call(this,"product")};
$jscomp.inherits(ProductEntity,EntityBase);var StageEntity=function(){EntityBase.call(this,"stage")};$jscomp.inherits(StageEntity,EntityBase);
var Battery=function(a,b){Enemy.call(this,a,b);this.speed=0;this.hitPoint=1;this.score=10;this.anim=[new Animator(this,"enemy/battery.png"),new Animator(this,"enemy/batteryBase.png",Animator.TYPE.NONE)];this.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO)];this.isInverse=!1;(a=Field.Instance)&&a.landform&&(b={x:this.x,y:this.y+Landform.BRICK_WIDTH},a.landform.hitTest(b),this.isInverse=!b.walled)};$jscomp.inherits(Battery,Enemy);Battery.DEG_STEP=Enemy.DEG_STEP;
Battery.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Battery.assign=Enemy.assign;Battery.LIST=Enemy.LIST;Battery.MAX_TYPE=Enemy.MAX_TYPE;Battery.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Battery.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Battery.prototype.drawNormal=function(a){this.isInverse?this.radian<-Math.SQ?this.radian=Math.PI:0>this.radian&&(this.radian=0):Math.SQ<this.radian?this.radian=Math.PI:0<this.radian&&(this.radian=0);Enemy.prototype.drawNormal.call(this,a)};
var Bouncer=function(a,b){Enemy.call(this,a,b);this.dir=0>=this.x?0:Math.PI;this.speed=2;this.gravity=.1;this.reaction=.95;this.hitPoint=3;this.score=500;this.shuttle=2;this.img.src="/img/enemy/bouncer.png"};$jscomp.inherits(Bouncer,Enemy);Bouncer.DEG_STEP=Enemy.DEG_STEP;Bouncer.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Bouncer.assign=Enemy.assign;Bouncer.LIST=Enemy.LIST;Bouncer.MAX_TYPE=Enemy.MAX_TYPE;Bouncer.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Bouncer.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
Bouncer.prototype.move=function(a){this.shuttle&&(0>this.x||Field.Instance.width+Landform.BRICK_WIDTH<this.x)&&(this.dir=Math.trim(this.dir+Math.PI),this.x=this.svX,this.shuttle--);this.walled&&(this.x=this.svX,this.y=this.svY);return Enemy.prototype.move.call(this,a)};Bouncer.prototype.drawNormal=function(a){var b=Math.abs(this.dy),b=5>b?.75+b/20:1;a.save();a.scale(1,b);a.drawImage(this.img,-this.hW,-this.hH);a.restore();Enemy.prototype.drawNormal.call(this,a)};
var Charger=function(a,b){Enemy.call(this,a,b);this.speed=2.5;this.hitPoint=1;this.score=10;this.anim=new Animator(this,"enemy/charger.png");this.routine=[(new Movement(Movement.COND.Y)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_Y).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_Y),(new Movement(10)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_X).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(1E3)).add(Gizmo.TYPE.OWN,Gizmo.DEST.TO)]};$jscomp.inherits(Charger,Enemy);Charger.DEG_STEP=Enemy.DEG_STEP;Charger.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;
Charger.assign=Enemy.assign;Charger.LIST=Enemy.LIST;Charger.MAX_TYPE=Enemy.MAX_TYPE;Charger.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Charger.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
var Crab=function(a,b){Enemy.call(this,a,b);this.hasBounds=!1;this.gravity=.3;this.reaction=.4;this.speed=2;this.hitPoint=1;this.score=90;this.anim=new Animator(this,"enemy/crab.png",Animator.TYPE.X|Animator.TYPE.ROTATION,8,1);this.routine=[(new Movement(Movement.COND.X)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(Crab.WALK)).add(Gizmo.TYPE.OWN,Gizmo.DEST.RIGHT),(new Movement(Movement.COND.X)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(Crab.WALK)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.LEFT)]};
$jscomp.inherits(Crab,Enemy);Crab.DEG_STEP=Enemy.DEG_STEP;Crab.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Crab.assign=Enemy.assign;Crab.LIST=Enemy.LIST;Crab.MAX_TYPE=Enemy.MAX_TYPE;Crab.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Crab.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Crab.WALK=20;var DragonBody=function(a,b){Enemy.call(this,a,b);this.region=new Region(this,16);this.effectV=this.effectH=this.hasBounds=!1;this.hitPoint=Number.MAX_SAFE_INTEGER;this.score=0;this.anim=new Animator(this,"enemy/dragonBody.png")};
$jscomp.inherits(DragonBody,Enemy);DragonBody.DEG_STEP=Enemy.DEG_STEP;DragonBody.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;DragonBody.assign=Enemy.assign;DragonBody.LIST=Enemy.LIST;DragonBody.MAX_TYPE=Enemy.MAX_TYPE;DragonBody.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;DragonBody.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;$jscomp.global.Object.defineProperties(DragonBody.prototype,{triggered:{configurable:!0,enumerable:!0,get:function(){return!1}}});
var DragonHead=function(a,b){Enemy.call(this,a,b);this.region=new Region(this,16);this.x=0<this.x?this.x+50:this.x-50;this.hasBounds=!1;this.speed=.9;this.effectH=!1;this.hitPoint=200;this.score=1E4;this.radian=Math.PI;this.appears=!1;this.anim=new Animator(this,"enemy/dragonHead.png");this.locus=[];this.body=[];for(a=0;a<DragonHead.CNT_OF_BODY*DragonHead.STP_OF_BODY;a++)this.locus.push({x:this.x,y:this.y,radian:this.radian}),0==a%DragonHead.STP_OF_BODY&&(b=new DragonBody(this.x,this.y),this.body.push(b));
this.chamberList=[new Chamber(TitanShot,80,1)]};$jscomp.inherits(DragonHead,Enemy);DragonHead.DEG_STEP=Enemy.DEG_STEP;DragonHead.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;DragonHead.assign=Enemy.assign;DragonHead.LIST=Enemy.LIST;DragonHead.MAX_TYPE=Enemy.MAX_TYPE;DragonHead.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;DragonHead.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;DragonHead.prototype.eject=function(){Enemy.prototype.eject.call(this);this.body.forEach(function(a){a.hitPoint=0;a.explosion=Actor.MAX_EXPLOSION})};
DragonHead.prototype.move=function(a){var b=this,c=Math.trim(this.radian+.9*this.closeGap(a));this.radian=this.dir=c;Enemy.prototype.move.call(this,a);this.chamberList.forEach(function(a){a.probe()});for(a=0;a<DragonHead.CNT_OF_BODY;a++){var c=this.body[a],d=this.locus[(a+1)*DragonHead.STP_OF_BODY-1];c.x=d.x;c.y=d.y;c.radian=d.radian}this.locus.unshift({x:this.x,y:this.y,radian:this.radian});this.locus.pop();if(this.appears){var e=[];this.chamberList.forEach(function(a){if(a=a.fire(b))a.dir=b.dir,
a.radian=b.dir,e.push(a)});return e}this.appears=!0;return this.body};DragonHead.CNT_OF_BODY=10;DragonHead.STP_OF_BODY=32;ImageManager.Instance.reserve("enemy/dragonHead.png","enemy/dragonBody.png");var Hanker=function(a,b){Enemy.call(this,a,b);this.speed=.7;this.hitPoint=2;this.score=50;this.anim=new Animator(this,"enemy/hanker.png");this.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO)]};$jscomp.inherits(Hanker,Enemy);Hanker.DEG_STEP=Enemy.DEG_STEP;
Hanker.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Hanker.assign=Enemy.assign;Hanker.LIST=Enemy.LIST;Hanker.MAX_TYPE=Enemy.MAX_TYPE;Hanker.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Hanker.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
var Hatch=function(a,b){Enemy.call(this,a,b);this.region=new Region(this,12);this.speed=0;this.hitPoint=10;this.score=200;this.children=this.count=0;this.anim=new Animator(this,"enemy/hatch.png",Animator.TYPE.Y,1,2);this.isInverse=!1;(a=Field.Instance)&&a.landform&&(b={x:this.x,y:this.y+Landform.BRICK_WIDTH},a.landform.hitTest(b),this.isInverse=!b.walled)};$jscomp.inherits(Hatch,Enemy);Hatch.DEG_STEP=Enemy.DEG_STEP;Hatch.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Hatch.assign=Enemy.assign;Hatch.LIST=Enemy.LIST;
Hatch.MAX_TYPE=Enemy.MAX_TYPE;Hatch.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Hatch.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Hatch.prototype.move=function(a){Enemy.prototype.move.call(this,a);if(!(this.count++<Hatch.IDLE||0!=this.count%Hatch.INTERVAL||Hatch.CHILDREN<=this.children++||0<this.explosion))return[new Charger(this.x,this.y)]};Hatch.IDLE=80;Hatch.INTERVAL=12;Hatch.CHILDREN=20;
var Jerky=function(a,b){Enemy.call(this,a,b);this.hitPoint=this.speed=1;this.score=10;this.anim=new Animator(this,"enemy/jerky.png");this.routine=[(new Movement(Movement.COND.X)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_X).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_X),(new Movement(Movement.COND.Y)).add(Gizmo.TYPE.AIM,Gizmo.DEST.TO_Y).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO_Y)]};$jscomp.inherits(Jerky,Enemy);Jerky.DEG_STEP=Enemy.DEG_STEP;Jerky.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Jerky.assign=Enemy.assign;Jerky.LIST=Enemy.LIST;
Jerky.MAX_TYPE=Enemy.MAX_TYPE;Jerky.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Jerky.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;var Juno=function(a,b){Enemy.call(this,a,b);this.hasBounds=!1;this.dir=Math.PI;this.speed=1;this.hitPoint=16;this.score=7500;this.anim=new Animator(this,"enemy/juno.png");this.routine=[(new Movement(200)).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO),(new Movement(Number.MAX_VALUE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)]};$jscomp.inherits(Juno,Enemy);Juno.DEG_STEP=Enemy.DEG_STEP;
Juno.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Juno.assign=Enemy.assign;Juno.LIST=Enemy.LIST;Juno.MAX_TYPE=Enemy.MAX_TYPE;Juno.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Juno.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
var Slur=function(a,b){Enemy.call(this,a,b);this.hasBounds=!1;this.dir=0>=this.x?0:Math.PI;this.step=Math.PI/8;this.speed=2;this.hitPoint=3;this.score=300;this.anim=new Animator(this,"enemy/slur.png");this.routine=[(new Movement(Slur.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(4*Slur.RANGE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE),(new Movement(Slur.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(4*
Slur.RANGE)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)]};$jscomp.inherits(Slur,Enemy);Slur.DEG_STEP=Enemy.DEG_STEP;Slur.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Slur.assign=Enemy.assign;Slur.LIST=Enemy.LIST;Slur.MAX_TYPE=Enemy.MAX_TYPE;Slur.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Slur.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Slur.RANGE=4;
var Tentacle=function(a,b){Chain.call(this,a,b);this.hasBounds=!1;this.speed=.1;this.hitPoint=16;this.appears=!1;this.anim=new Animator(this,"enemy/tentacle.png");this.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.TO).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE,Tentacle.DEG_STEP)];this.push(new TentacleHead(0));for(a=0;a<Tentacle.MAX_JOINT;a++)b=Tentacle.MAX_JOINT-a,this.push(new TentacleJoint(b*b));this.score=150};$jscomp.inherits(Tentacle,Chain);Tentacle.MAX_EXPLOSION=Chain.MAX_EXPLOSION;
Tentacle.assign=Chain.assign;Tentacle.LIST=Chain.LIST;Tentacle.MAX_TYPE=Chain.MAX_TYPE;Tentacle.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;Tentacle.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;Tentacle.prototype.eject=function(){for(var a=this.next;a;)a.eject(),a=a.next;this.isGone=!0;this.x=-this.width};Tentacle.prototype.calcRadian=function(){return this.radian};Tentacle.prototype.calcRelative=function(){return this.radian};
Tentacle.prototype.move=function(a){this.radius=this.hitPoint/2+8;this.scale=this.radius/Tentacle.MAX_RADIUS;this.region=new Region(this,this.radius);Chain.prototype.move.call(this,a);if(!this.appears){this.appears=!0;a=[];for(var b=this.next;b;)a.push(b),b=b.next;return a}};Tentacle.MAX_JOINT=8;Tentacle.MAX_RADIUS=16;Tentacle.DEG_STEP=Math.PI/900;var TentacleJoint=function(a){Chain.call(this,0,0);this.hasBounds=!1;this.radius=4;this.radian=0;this.speed=a;this.anim=new Animator(this,"enemy/tentacleJoint.png")};
$jscomp.inherits(TentacleJoint,Chain);TentacleJoint.MAX_EXPLOSION=Chain.MAX_EXPLOSION;TentacleJoint.assign=Chain.assign;TentacleJoint.LIST=Chain.LIST;TentacleJoint.MAX_TYPE=Chain.MAX_TYPE;TentacleJoint.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;TentacleJoint.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;TentacleJoint.prototype.calcRadian=function(){return Math.trim(this.prev.calcRadian()+this.radian)};TentacleJoint.prototype.calcRelative=function(){return Math.trim(this.radian-this.prev.calcRadian())};
TentacleJoint.prototype.rotate=function(a){var b=this.calcRadian();this.radian=Math.close(b,Math.atan2(a.y-this.y,a.x-this.x),TentacleJoint.DEG_STEP*this.speed);this.radian=this.calcRelative();this.radian<-TentacleJoint.MAX_RAD&&(this.radian=-TentacleJoint.MAX_RAD);TentacleJoint.MAX_RAD<this.radian&&(this.radian=TentacleJoint.MAX_RAD)};TentacleJoint.prototype.move=function(a){var b=this.prev,c=b.calcRadian(),d=b.radius+this.radius;this.x=b.x+Math.cos(c)*d;this.y=b.y+Math.sin(c)*d;return this.rotate(a)};
TentacleJoint.prototype.fate=function(){};TentacleJoint.DEG_STEP=Math.PI/18E3;TentacleJoint.MAX_RAD=Math.PI/6;var TentacleBullet=function(a,b){Bullet.call(this,a,b);this.region=new Region(this,1);this.speed=.5;this.width=2;this.fillStyle="rgba(255, 200, 200, 0.7)"};$jscomp.inherits(TentacleBullet,Bullet);TentacleBullet.DEG_STEP=Bullet.DEG_STEP;TentacleBullet.MAX_EXPLOSION=Bullet.MAX_EXPLOSION;
var TentacleHead=function(a){TentacleJoint.call(this,a);this.anim=new Animator(this,"enemy/tentacleHead.png");this.chamberList=[new Chamber(TentacleBullet,TentacleHead.TRIGGER_CYCLE)]};$jscomp.inherits(TentacleHead,TentacleJoint);TentacleHead.MAX_EXPLOSION=TentacleJoint.MAX_EXPLOSION;TentacleHead.assign=TentacleJoint.assign;TentacleHead.LIST=TentacleJoint.LIST;TentacleHead.MAX_TYPE=TentacleJoint.MAX_TYPE;TentacleHead.TRIGGER_ALLOWANCE=TentacleJoint.TRIGGER_ALLOWANCE;TentacleHead.MAX_RAD=TentacleJoint.MAX_RAD;
TentacleHead.prototype.rotate=function(a){this.radian=Math.close(this.radian,Math.atan2(a.y-this.y,a.x-this.x),TentacleHead.DEG_STEP);return this.trigger(a)};TentacleHead.TRIGGER_CYCLE=10;TentacleHead.DEG_STEP=Math.PI/100;ImageManager.Instance.reserve("enemy/tentacle.png","enemy/tentacleHead.png");
var Twister=function(a,b){Enemy.call(this,a,b);this.hasBounds=!1;this.dir=0>=this.x?0:Math.PI;this.step=Math.PI/23;this.speed=3;this.score=100;this.anim=new Animator(this,"enemy/twister.png");this.routine=[(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R).add(Gizmo.TYPE.FIXED,
Gizmo.DEST.ROTATE),(new Movement(Twister.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L).add(Gizmo.TYPE.FIXED,Gizmo.DEST.ROTATE)]};$jscomp.inherits(Twister,Enemy);Twister.DEG_STEP=Enemy.DEG_STEP;Twister.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Twister.assign=Enemy.assign;Twister.LIST=Enemy.LIST;Twister.MAX_TYPE=Enemy.MAX_TYPE;Twister.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Twister.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Twister.RANGE=13;
var Waver=function(a,b){Enemy.call(this,a,b);this.dir=0>=this.x?0:Math.PI;this.step=Math.PI/60;this.speed=2.5;this.score=100;this.anim=new Animator(this,"enemy/waver.png",Animator.TYPE.Y,1,8);this.routine=[(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R),(new Movement(Waver.RANGE)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_L)]};
$jscomp.inherits(Waver,Enemy);Waver.DEG_STEP=Enemy.DEG_STEP;Waver.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Waver.assign=Enemy.assign;Waver.LIST=Enemy.LIST;Waver.MAX_TYPE=Enemy.MAX_TYPE;Waver.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Waver.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Waver.RANGE=18;var MissileCapsule=function(a){Capsule.call(this,a);this.anim=new Animator(this,"capsule/missileCapsule.png",Animator.TYPE.Y)};$jscomp.inherits(MissileCapsule,Capsule);MissileCapsule.DEG_STEP=Capsule.DEG_STEP;
MissileCapsule.MAX_EXPLOSION=Capsule.MAX_EXPLOSION;MissileCapsule.RANGE=Capsule.RANGE;MissileCapsule.prototype.fate=function(a){a.powerUpMissile();this.eject()};var SpeedupCapsule=function(a){Capsule.call(this,a);this.anim=new Animator(this,"capsule/speedupCapsule.png",Animator.TYPE.Y)};$jscomp.inherits(SpeedupCapsule,Capsule);SpeedupCapsule.DEG_STEP=Capsule.DEG_STEP;SpeedupCapsule.MAX_EXPLOSION=Capsule.MAX_EXPLOSION;SpeedupCapsule.RANGE=Capsule.RANGE;
SpeedupCapsule.prototype.fate=function(a){a.speedup();this.eject()};var Molten=function(a,b){Enemy.call(this,a,b);this.region=new Region(this,14);this.hasBounds=!1;this.dir=0;this.speed=.4;this.effectH=!1;this.hitPoint=Number.MAX_SAFE_INTEGER;this.cycle=0;this.phase=Molten.PHASE.TARGET;this.rock=[];this.appears=!1;this.anim=new Animator(this,"boss/molten.png");this.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)]};$jscomp.inherits(Molten,Enemy);Molten.DEG_STEP=Enemy.DEG_STEP;
Molten.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Molten.assign=Enemy.assign;Molten.LIST=Enemy.LIST;Molten.MAX_TYPE=Enemy.MAX_TYPE;Molten.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Molten.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Molten.prototype.move=function(a){Enemy.prototype.move.call(this,a);Molten.MAX_CYCLE<this.cycle++&&(this.cycle=0,this.phase++,this.phase%=Molten.PHASE.length);if(this.appears)return this.checkDestroy(a),[];this.appears=!0;a=new MoltenRock(this,this.x,this.y);this.rock=[a];return[a]};
Molten.prototype.checkDestroy=function(a){var b=[];this.rock.forEach(function(a){a.isGone||b.push(a)});0==b.length&&(this.hitPoint=0,this.fate(a));this.rock=b};Molten.MAX_CYCLE=700;Molten.PHASE={OWN:0,TARGET:1,length:2};var MoltenRock=function(a,b,c){Enemy.call(this,b,c);this.hasBounds=!1;this.parent=a;this.dir=0;this.speed=.6;this.hitPoint=5;this.score=10;this.anim=new Animator(this,"boss/moltenRock.png");this.routine=[(new Movement).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE)]};
$jscomp.inherits(MoltenRock,Enemy);MoltenRock.DEG_STEP=Enemy.DEG_STEP;MoltenRock.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;MoltenRock.assign=Enemy.assign;MoltenRock.LIST=Enemy.LIST;MoltenRock.MAX_TYPE=Enemy.MAX_TYPE;MoltenRock.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;MoltenRock.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
MoltenRock.prototype.move=function(a){var b=[],c=this.parent;c.phase==Molten.PHASE.OWN?b=Enemy.prototype.move.call(this,c):Enemy.prototype.move.call(this,a);if(this.absorbed&&this.hitPoint){a=Math.trim(this.dir+Math.SQ);for(var d=0;3>d;d++){var e=new MoltenRock(c,this.x,this.y);e.dir=a;e.speed=1.2*this.speed;e.hitPoint=this.hitPoint;b.push(e);c.rock.push(e);a=Math.trim(a+Math.SQ)}}this.absorbed=!1;return b};function MotionManager(){Repository.apply(this,arguments)}MotionManager.prototype=Object.create(Repository.prototype);
MotionManager.INSTANCE=new MotionManager;MotionManager.prototype.makeName=function(a){return"/motion/"+a+".json"};function Motion(a,b,c,d){this.type=a;this.key=b;this.speed=c;this.h=d;this.y=this.x=this.v=0;this.triggerMax=this.triggerMin=Number.NaN;this.filling=this.reserve=null;this.batter=0}Motion.TYPE={NORMAL:0,ONLY_ONE:1,REWIND:2};Motion.prototype.rotateV=function(a){this.v=a;return this};Motion.prototype.offsetX=function(a){this.x=a;return this};
Motion.prototype.offsetY=function(a){this.y=a;return this};Motion.prototype.shot=function(a,b,c){this.reserve={type:a,id:b};isFinite(c)?(this.triggerMin=c,this.triggerMax=c+this.speed):(this.triggerMin=c.min,this.triggerMax=c.max);return this};Motion.prototype.reset=function(){if(this.mot=MotionManager.INSTANCE.dic[this.key])this.max=this.mot.length-1;this.ix=0;this.dir=1;return this};
Motion.prototype.next=function(){var a=this.ix+this.speed*this.dir;if(this.max<=a){if(this.type!=Motion.TYPE.REWIND)return null;this.ix=this.max;this.dir*=-1;return[this.mot[this.ix]]}if(0>a)return null;for(var b=[];this.ix!=a;)this.ix+=this.dir,b.push(this.mot[this.ix]);this.checkTrigger();return b};Motion.prototype.checkTrigger=function(){this.filling||(0<this.batter?this.batter=0:this.triggerMin<=this.ix&&this.ix<=this.triggerMax&&(this.filling=this.reserve,this.batter=1))};
Motion.prototype.fire=function(){if(this.filling){var a=this.filling;this.filling=null;return a}};function MotionRoutine(a){this.routine=a;this.ix=0;this.max=this.routine.length-1;this.loop=0;this.current=this.routine[this.ix].reset()}
MotionRoutine.prototype.next=function(a){var b=this.current.ix,c=this.current.next();null==c&&(this.ix++,this.max<this.ix&&(this.ix=0,this.loop++),this.current=this.routine[this.ix].reset(),0<this.loop&&this.current.type==Motion.TYPE.ONLY_ONE&&(this.ix++,this.current=this.routine[this.ix].reset()),c=this.current.next());var d=this.current.ix<b?-1:1,b=this.current.fire();a.rotationH=this.current.h;a.rotationV=this.current.v;a.offsetX=this.current.x;a.offsetY=this.current.y;a.calcRotationMatrix();c.forEach(function(b){a.shift(b,
d);a.calculate()});return b};function Skeleton(a){this.data=a;this.map={};this.offsetY=this.offsetX=0;this.rotationH=Math.PI/4;this.rotationV=Math.PI/8;this.rotationMatrix=new Matrix(Matrix.NO_EFFECT);this.init()}Skeleton.prototype.init=function(){var a=Object.assign(new Bone,this.data.root);this.data.root=a;this.prepare(a);this.calcRotationMatrix()};
Skeleton.prototype.prepare=function(a){var b=this,c=[];a.prepare();a.joint.forEach(function(b){b.parent=a;c.push(Object.assign(new Bone,b))});a.joint=c;a.joint.forEach(function(a){b.prepare(a)});a.skeleton=this;this.map[a.name]=a};Skeleton.prototype.calcRotationMatrix=function(){var a=Matrix.rotateY(this.rotationH);this.rotationMatrix=Matrix.rotateX(this.rotationV).multiply(a)};Skeleton.prototype.rotateH=function(a){this.rotationH+=Math.PI/720*a;this.rotationH=Math.trim(this.rotationH);this.calcRotationMatrix()};
Skeleton.prototype.rotateV=function(a){this.rotationV+=Math.PI/720*a;this.rotationV=Math.trim(this.rotationV);this.calcRotationMatrix()};Skeleton.prototype.shift=function(a,b){var c=this;a.forEach(function(a){var d=a.r,f=c.map[a.name],g=Matrix.rotateX(d.x),h=Matrix.rotateY(d.y),d=Matrix.rotateZ(d.z);f.motionMatrix=d.multiply(h).multiply(g);a.p&&(a=a.p,g=f.pt,f.translateMatrix=new Matrix([[1,0,0,c.offsetX+g.x+a.x*b],[0,1,0,c.offsetY+g.y+a.y*b],[0,0,1,g.z+a.z*b],[0,0,0,1]]))})};
Skeleton.prototype.calculate=function(a){this.data.root.calculate(a)};Skeleton.prototype.draw=function(a){this.data.root.draw(a)};function Bone(){this.pt={x:0,y:0,z:0}}
Bone.prototype.prepare=function(){var a=this.translate,b=Matrix.rotateX(this.axis.x),c=Matrix.rotateY(this.axis.y),b=Matrix.rotateZ(this.axis.z).multiply(c).multiply(b);this.translateMatrix=new Matrix([[1,0,0,a.x],[0,1,0,a.y],[0,0,1,a.z],[0,0,0,1]]);if(this.parent){var d=this.parent,a=Matrix.rotateX(-d.axis.x),c=Matrix.rotateY(-d.axis.y),d=Matrix.rotateZ(-d.axis.z);this.axisMatrix=a.multiply(c).multiply(d).multiply(b)}else this.axisMatrix=b;this.motionMatrix=new Matrix(Matrix.NO_EFFECT)};
Bone.prototype.getAccum=function(){if(this.parent){var a=this.axisMatrix.multiply(this.motionMatrix).multiply(this.translateMatrix);return this.parent.getAccum().multiply(a)}return this.translateMatrix.multiply(this.motionMatrix)};Bone.prototype.calculate=function(a){this.pt=this.getAccum().affine(0,0,0);a||this.joint.forEach(function(a){a.calculate(!1)})};
Bone.prototype.drawLine=function(a){var b=this.parent.pt,c=this.pt,d=this.skeleton.rotationMatrix,b=d.affine(b.x,b.y,b.z),c=d.affine(c.x,c.y,c.z),d=c.x,e=-c.y,f=b.x,b=-b.y,g=d-f,h=e-b;this.cx=f+g/2;this.cy=b+h/2;this.cz=c.z;this.radian=Math.atan2(h,g);a.beginPath();a.moveTo(f,b);a.lineTo(d,e);a.stroke()};Bone.prototype.draw=function(a){this.calculate();this.parent&&this.drawLine(a);this.joint.forEach(function(b){b.draw(a)})};
var Titan=function(a,b){Enemy.call(this,a,b);this.scale=7;this.hitPoint=Number.MAX_SAFE_INTEGER;this.motionRoutine=new MotionRoutine([(new Motion(Motion.TYPE.ONLY_ONE,"111_7.amc",2,Math.PI/4)).offsetX(0).offsetY(0),(new Motion(Motion.TYPE.NORMAL,"79_96.amc",1,.4*-Math.PI)).shot(TitanShot,["lradius","lwrist","lhand","lthumb","lfingers"],200),(new Motion(Motion.TYPE.REWIND,"133_01.amc",2,Math.PI)).shot(TitanBullet,["thorax","upperneck"],{min:200,max:550}),(new Motion(Motion.TYPE.NORMAL,"79_91.amc",
1,.4*-Math.PI)).shot(TitanBall,["rhumerus","rradius","rwrist","rhand"],{min:175,max:200}),(new Motion(Motion.TYPE.NORMAL,"86_01b.amc",2,Math.PI)).shot(Bullet,["lfingers","rfingers"],{min:0,max:1E3})]);if(a=Object.assign({},MotionManager.INSTANCE.dic.asf))this.skeleton=new Skeleton(a),this.setupBone()};$jscomp.inherits(Titan,Enemy);Titan.DEG_STEP=Enemy.DEG_STEP;Titan.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Titan.assign=Enemy.assign;Titan.LIST=Enemy.LIST;Titan.MAX_TYPE=Enemy.MAX_TYPE;
Titan.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Titan.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Titan.prototype.setupBone=function(){var a={};Object.keys(this.skeleton.map).forEach(function(b){if("root"!=b){var c=new TitanBone(b,0,0);b==Titan.CORE&&(c.hitPoint=Titan.HIT_POINT);a[b]=c}});this.boneMap=a;this.appears=!1};Titan.prototype.eject=function(){var a=this;Enemy.prototype.eject.call(this);Object.keys(this.boneMap).forEach(function(b){b=a.boneMap[b];b.hitPoint=0;b.explosion=2*Actor.MAX_EXPLOSION})};
Titan.prototype.move=function(a){var b=this,c=[],d=this.motionRoutine.next(this.skeleton);Enemy.prototype.move.call(this,a);if(!this.appears)return Object.keys(this.boneMap).forEach(function(a){c.push(b.boneMap[a])}),this.appears=!0,c.reverse();var e=this.skeleton.map,f=!1;d&&d.id.forEach(function(a){a=b.boneMap[a];var e=new d.type(a.x,a.y);e.dir=a.radian;c.push(e)});Object.keys(this.boneMap).forEach(function(a){var c=e[a],d=c.cy*b.scale+b.y;a=b.boneMap[a];a.x=c.cx*b.scale+b.x;a.y=d;a.z=c.cz;a.radian=
c.radian;0==a.hitPoint&&(f=!0)});f&&this.eject();return c};Titan.prototype.drawInfo=function(a){var b=this.motionRoutine.current,c=this.boneMap[Titan.CORE];a.save();a.translate(this.x,this.y);a.strokeStyle="rgba(255, 255, 255, 0.8)";a.strokeText("ix:"+b.ix,0,0);a.strokeText("hp:"+c.hitPoint,0,10);a.restore()};Titan.prototype.drawNormal=function(a){a.save();a.translate(this.x,this.y);this.skeleton&&(a.scale(this.scale,this.scale),a.strokeStyle="rgba(203, 152, 135, 0.2)",this.skeleton.draw(a));a.restore()};
Titan.prototype.isHit=function(a){return!1};Titan.HIT_POINT=292;Titan.CORE="lowerback";var TitanBone=function(a,b,c){var d="boss/titan/"+a+".png";Enemy.call(this,b,c);this.id=a;this.hasBounds=!1;this.hitPoint=Number.MAX_SAFE_INTEGER;this.filling=null;this.anim=new Animator(this,d)};$jscomp.inherits(TitanBone,Enemy);TitanBone.DEG_STEP=Enemy.DEG_STEP;TitanBone.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;TitanBone.assign=Enemy.assign;TitanBone.LIST=Enemy.LIST;TitanBone.MAX_TYPE=Enemy.MAX_TYPE;
TitanBone.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;TitanBone.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;TitanBone.prototype.drawNormal=function(a){Enemy.prototype.drawNormal.call(this,a)};$jscomp.global.Object.defineProperties(TitanBone.prototype,{triggered:{configurable:!0,enumerable:!0,get:function(){return!1}}});
ImageManager.Instance.reserve("boss/titan/head.png","boss/titan/lclavicle.png","boss/titan/lfemur.png","boss/titan/lfingers.png","boss/titan/lfoot.png","boss/titan/lhand.png","boss/titan/lhipjoint.png","boss/titan/lhumerus.png","boss/titan/lowerback.png","boss/titan/lowerneck.png","boss/titan/lradius.png","boss/titan/lthumb.png","boss/titan/ltibia.png","boss/titan/ltoes.png","boss/titan/lwrist.png","boss/titan/rclavicle.png","boss/titan/rfemur.png","boss/titan/rfingers.png","boss/titan/rfoot.png",
"boss/titan/rhand.png","boss/titan/rhipjoint.png","boss/titan/rhumerus.png","boss/titan/rradius.png","boss/titan/rthumb.png","boss/titan/rtibia.png","boss/titan/rtoes.png","boss/titan/rwrist.png","boss/titan/thorax.png","boss/titan/upperback.png","boss/titan/upperneck.png");var TitanBall=function(a,b){Enemy.call(this,a,b);this.hasBounds=!1;this.speed=1.5+4*Math.random();this.gravity=.03;this.hitPoint=4;this.anim=new Animator(this,"boss/titan/titan.ball.png")};$jscomp.inherits(TitanBall,Enemy);
TitanBall.DEG_STEP=Enemy.DEG_STEP;TitanBall.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;TitanBall.assign=Enemy.assign;TitanBall.LIST=Enemy.LIST;TitanBall.MAX_TYPE=Enemy.MAX_TYPE;TitanBall.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;TitanBall.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;TitanBall.prototype.reactY=function(a){Enemy.prototype.reactY.call(this,a);this.fate(this)};$jscomp.global.Object.defineProperties(TitanBall.prototype,{triggered:{configurable:!0,enumerable:!0,get:function(){return!1}}});
var TitanBullet=function(a,b){Enemy.call(this,a,b);this.radian=this.dir=-Math.PI+Math.SQ/2;this.speed=4;this.hitPoint=Number.MAX_SAFE_INTEGER;this.anim=new Animator(this,"boss/titan/titan.bullet.png")};$jscomp.inherits(TitanBullet,Enemy);TitanBullet.DEG_STEP=Enemy.DEG_STEP;TitanBullet.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;TitanBullet.assign=Enemy.assign;TitanBullet.LIST=Enemy.LIST;TitanBullet.MAX_TYPE=Enemy.MAX_TYPE;TitanBullet.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;TitanBullet.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
$jscomp.global.Object.defineProperties(TitanBullet.prototype,{triggered:{configurable:!0,enumerable:!0,get:function(){return!1}}});var TitanShot=function(a,b){Enemy.call(this,a,b);this.radian=this.dir=Math.PI;this.speed=7;this.hitPoint=Number.MAX_SAFE_INTEGER;this.anim=new Animator(this,"boss/titan/titan.shot.png")};$jscomp.inherits(TitanShot,Enemy);TitanShot.DEG_STEP=Enemy.DEG_STEP;TitanShot.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;TitanShot.assign=Enemy.assign;TitanShot.LIST=Enemy.LIST;
TitanShot.MAX_TYPE=Enemy.MAX_TYPE;TitanShot.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;TitanShot.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;
var Winding=function(a,b){Chain.call(this,a,b);this.region=new Region(this,12);this.dir=-Math.PI;this.step=Math.SQ/100;this.radius=Winding.RADIUS;this.speed=.5;this.hitPoint=100;this.hasBounds=!1;this.ratio=Winding.RATIO_MAX;this.delta=-1;this.uncoil=!1;this.anim=new Animator(this,"boss/winding.png");this.routine=[(new Movement(200)).add(Gizmo.TYPE.CHASE,Gizmo.DEST.ROTATE,Math.PI/180),(new Movement(20)).add(Gizmo.TYPE.OWN,Gizmo.DEST.ROTATE_R)];this.chamberList=[new Chamber(Slur,Winding.TRIGGER_CYCLE)];
this.init()};$jscomp.inherits(Winding,Chain);Winding.DEG_STEP=Chain.DEG_STEP;Winding.MAX_EXPLOSION=Chain.MAX_EXPLOSION;Winding.assign=Chain.assign;Winding.LIST=Chain.LIST;Winding.MAX_TYPE=Chain.MAX_TYPE;Winding.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;Winding.prototype.init=function(){this.appears=!1;for(var a=0;a<Winding.MAX_JOINT;a++)this.push(new WindingChild(this.x,this.y))};
Winding.prototype.move=function(a){var b=Chain.prototype.move.call(this,a),c=Math.trim(this.dir-Math.SQ/2);this.rad=Math.trim(this.dir+Math.SQ);if(this.appears){for(var d=this.next;d;)c+=Winding.RADIAN_STEP*this.ratio/100,d.radian=Math.trim(c),d=d.next;this.uncoil&&(this.ratio+=this.delta,1>=this.ratio?this.delta*=-1:Winding.RATIO_MAX<=this.ratio&&(this.uncoil=!1,this.delta*=-1,b=this.trigger(a,!0),b.forEach(function(b){b.aim(a);b.dir=Math.trim(b.dir+Math.PI)})));return b}this.appears=!0;for(c=this.next;c;)b.push(c),
c=c.next;return b};Winding.prototype.fate=function(a){Chain.prototype.fate.call(this,a);this.uncoil=!0};Winding.RADIUS=16;Winding.RADIAN_STEP=Math.SQ;Winding.RATIO_MAX=50;Winding.MAX_JOINT=20;Winding.TRIGGER_CYCLE=20;var WindingChild=function(a,b){Chain.call(this,a,b);this.effectH=this.hasBounds=!1;this.radius=WindingChild.RADIUS;this.anim=new Animator(this,"boss/winding.joint.png")};$jscomp.inherits(WindingChild,Chain);WindingChild.DEG_STEP=Chain.DEG_STEP;WindingChild.MAX_EXPLOSION=Chain.MAX_EXPLOSION;
WindingChild.assign=Chain.assign;WindingChild.LIST=Chain.LIST;WindingChild.MAX_TYPE=Chain.MAX_TYPE;WindingChild.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;WindingChild.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;WindingChild.prototype.move=function(a){a=this.prev;var b=this.radius+a.radius;this.x=a.x+Math.cos(this.radian)*b;this.y=a.y+Math.sin(this.radian)*b};WindingChild.prototype.fate=function(){};WindingChild.RADIUS=4;
var Cascade=function(a,b){Chain.call(this,a,b);this.anim=new Animator(this,"material/cascade.png");this.radian=Math.SQ;this.radius=Cascade.RADIUS;this.appears=!1;for(var c=0;c<Cascade.MAX_JOINT;c++)this.push(new CascadeChild(a,b,3*(Cascade.MAX_JOINT-c)))};$jscomp.inherits(Cascade,Chain);Cascade.DEG_STEP=Chain.DEG_STEP;Cascade.MAX_EXPLOSION=Chain.MAX_EXPLOSION;Cascade.assign=Chain.assign;Cascade.LIST=Chain.LIST;Cascade.MAX_TYPE=Chain.MAX_TYPE;Cascade.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;
Cascade.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;Cascade.prototype.move=function(a){Chain.prototype.move.call(this,a);if(!this.appears){this.appears=!0;a=[];for(var b=this.next;b;)a.push(b),b=b.next;return a}};Cascade.prototype.fate=function(){};Cascade.RADIUS=4;Cascade.MAX_JOINT=12;var CascadeChild=function(a,b,c){Chain.call(this,a,b);this.effectV=this.effectH=!1;this.weight=c;this.radian=.9*Math.SQ;this.radius=Cascade.RADIUS;this.step=0;Field.Instance&&(this.maxX=Field.Instance.width+100)};
$jscomp.inherits(CascadeChild,Chain);CascadeChild.DEG_STEP=Chain.DEG_STEP;CascadeChild.MAX_EXPLOSION=Chain.MAX_EXPLOSION;CascadeChild.assign=Chain.assign;CascadeChild.LIST=Chain.LIST;CascadeChild.MAX_TYPE=Chain.MAX_TYPE;CascadeChild.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;CascadeChild.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;CascadeChild.prototype.addRadian=function(a){return this.radian=Math.trim(this.radian+a)};
CascadeChild.prototype.move=function(a){a=this.prev;var b=Math.trim(Math.SQ-this.radian)/(300+10*this.weight);this.step+=b;0==parseInt(1E3*b)&&(this.step*=.98);var b=Math.trim(this.radian+this.step),c=this.radius+a.radius;0>b&&(b=0);this.radian=b;this.x=a.x+Math.cos(b)*c;this.y=a.y+Math.sin(b)*c};CascadeChild.prototype.draw=function(a){a.save();a.fillStyle="rgba(60, 200, 0, 0.8)";a.translate(this.x,this.y);a.beginPath();a.arc(0,0,this.radius,0,Math.PI2,!1);a.fill();a.restore()};
CascadeChild.prototype.fate=function(a){a=Math.PI/200;this.step-=a;for(var b=this.next;b;)b.step-=.8*a,b=b.next};
var Rewinder=function(a,b){Chain.call(this,a,b);this.step=Math.SQ/100;this.radius=Rewinder.RADIUS;this.speed=1.1;this.hitPoint=Number.MAX_SAFE_INTEGER;this.hasBounds=!1;this.ratio=Rewinder.RATIO_MAX;this.delta=-.8;this.anim=new Animator(this,"material/cascade.png");this.routine=[(new Movement).add(Gizmo.TYPE.AIM,Gizmo.DEST.ROTATE).add(Gizmo.TYPE.FIXED,Gizmo.DEST.TO)];this.appears=!1;for(var c=0;c<Rewinder.MAX_JOINT;c++)this.push(new RewinderChild(a,b))};$jscomp.inherits(Rewinder,Chain);
Rewinder.DEG_STEP=Chain.DEG_STEP;Rewinder.MAX_EXPLOSION=Chain.MAX_EXPLOSION;Rewinder.assign=Chain.assign;Rewinder.LIST=Chain.LIST;Rewinder.MAX_TYPE=Chain.MAX_TYPE;Rewinder.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;Rewinder.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;
Rewinder.prototype.move=function(a){var b=[],c=Math.trim(this.radian+Math.SQ/2);Chain.prototype.move.call(this,a);if(this.appears){for(a=this.next;a;)c-=Rewinder.RADIAN_STEP*this.ratio/100,a.radian=Math.trim(c),a=a.next;this.ratio+=this.delta;1>=this.ratio?this.delta*=-1:Rewinder.RATIO_MAX<=this.ratio&&(this.delta*=-1);return b}this.appears=!0;for(a=this.next;a;)b.push(a),a=a.next;return b};Rewinder.prototype.fate=function(){};Rewinder.RADIUS=4;Rewinder.RADIAN_STEP=Math.SQ;Rewinder.RATIO_MAX=100;
Rewinder.MAX_JOINT=16;var RewinderChild=function(a,b){Chain.call(this,a,b);this.radian=0;this.effectV=this.effectH=this.hasBounds=!1;this.radius=RewinderChild.RADIUS;this.anim=new Animator(this,"boss/winding.joint.png")};$jscomp.inherits(RewinderChild,Chain);RewinderChild.DEG_STEP=Chain.DEG_STEP;RewinderChild.MAX_EXPLOSION=Chain.MAX_EXPLOSION;RewinderChild.assign=Chain.assign;RewinderChild.LIST=Chain.LIST;RewinderChild.MAX_TYPE=Chain.MAX_TYPE;RewinderChild.TRIGGER_ALLOWANCE=Chain.TRIGGER_ALLOWANCE;
RewinderChild.TRIGGER_CYCLE=Chain.TRIGGER_CYCLE;RewinderChild.prototype.move=function(a){a=this.prev;var b=this.radius+a.radius;this.x=a.x+Math.cos(this.radian)*b;this.y=a.y+Math.sin(this.radian)*b};RewinderChild.prototype.fate=function(){};RewinderChild.RADIUS=4;AudioMixer.INSTANCE.reserve(["sfx-fire","sfx-explosion","sfx-absorb"]);MotionManager.INSTANCE.reserve("asf 79_91.amc 79_96.amc 86_01b.amc 111_7.amc 133_01.amc".split(" "));
