'use strict';var $jscomp={};$jscomp.scope={};$jscomp.getGlobal=function(a){return typeof window!="undefined"&&window===a?a:typeof global!="undefined"&&global!=null?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);if(e)Object.defineProperty(a,d,e)}else a[d]=b[d]};
var Matter=function(a,b,c){c=c===undefined?0:c;this.x=a;this.y=b;this.z=c;this.w=0;this.h=0;this.dy=0;this.dir=null;this.radian=0;this.gravity=0;this.speed=1};Matter.prototype.width;Matter.prototype.height;$jscomp.global.Object.defineProperties(Matter.prototype,{width:{configurable:true,enumerable:true,get:function(){return this.w},set:function(a){this.w=a;this.hW=a/2}},height:{configurable:true,enumerable:true,get:function(){return this.h},set:function(a){this.h=a;this.hH=a/2}}});
var Actor=function(a,b,c){c=c===undefined?0:c;Matter.call(this,a,b,c);var d=this;this.region=new Region(this);this.width=16;this.height=16;this.animList=[];this.chamberList=[];this.hasBounds=true;this.reaction=0;this.effectH=true;this.effectV=true;this.hitPoint=1;this.absorbed=false;this.score=0;this.walled=false;this.recalculation();this.img=new Image;this.img.addEventListener("load",function(){d.width=d.img.width;d.height=d.img.height;d.recalculation()});this.fillStyle=null;this.sfx="sfx-explosion";
this.sfxAbsorb="sfx-absorb";this.enter()};Actor.prototype.anim;$jscomp.inherits(Actor,Matter);Actor.prototype.recalculation=function(){var a=Field.Instance;if(a){var b=this.hasBounds?0:a.width;this.minX=-this.width-b;this.minY=-this.height-b;this.maxX=a.width+this.width+b;this.maxY=a.height+this.height+b}};Actor.prototype.enter=function(){this.explosion=0;this.isGone=false};Actor.prototype.eject=function(){this.isGone=true;this.x=Number.MIN_SAFE_INTEGER};
Actor.prototype.aim=function(a){if(a){var b=this.calcDistance(a);if(this.speed<b){var c=a.x-this.x;var d=a.y-this.y;this.dir=Math.atan2(d,c)}}else this.dir=null;return this};Actor.prototype.closeGap=function(a){var b=a.x-this.x;var c=a.y-this.y;var d=Math.trim(this.radian-Math.atan2(c,b));if(Math.abs(d)<=Actor.DEG_STEP)return 0;if(0<d)return-Actor.DEG_STEP;return Actor.DEG_STEP};Actor.prototype.reactX=function(a){this.dir=Math.trim(this.dir+Math.PI)};
Actor.prototype.reactY=function(a){this.y=a;this.dy*=-this.reaction;this.radian=Field.Instance.landform.getHorizontalAngle(this)};Actor.prototype.trigger=function(a,b){b=b===undefined?false:b;var c=this;var d=[];this.chamberList.forEach(function(e){return e.probe()});if(this.triggered||b){this.triggered=false;this.chamberList.forEach(function(e){var f=e.fire(c,a);if(f)d.push(f)})}return d};
Actor.prototype.move=function(a){var b=this;if(0<this.explosion){this.explosion--;if(this.explosion==0){this.eject();return}}this.svX=this.x;this.svY=this.y;if(this.dir!=null){this.x+=Math.cos(this.dir)*this.speed;this.y+=Math.sin(this.dir)*this.speed}if(this.gravity!=0){var c=Field.Instance.landform.scanFloor(this);var d=false;if(this.gravity<0){c+=this.hH;if(c<this.y)this.dy+=this.gravity;else if(this.y<c)d=true}else{c-=this.hH;if(this.y<c)this.dy+=this.gravity;else if(c<this.y)d=true}if(d){var e=
Math.abs(this.y-c);if(Landform.BRICK_WIDTH*2<e)this.reactX(c);else this.reactY(c)}}this.y+=this.dy*this.speed;this.animList.forEach(function(f){f.next(b.dir)});return this.trigger(a)};Actor.prototype.drawCircle=function(a){a.save();a.beginPath();a.fillStyle=this.fillStyle;a.arc(0,0,this.width,0,Math.PI*2,false);a.fill();a.restore()};Actor.prototype.drawHitPoint=function(a){if(this.hitPoint<1E5){a.save();a.fillStyle="white";a.fillText(this.hitPoint,0,20);a.restore()}};
Actor.prototype.drawNormal=function(a){this.animList.forEach(function(b){b.draw(a)});if(this.animList.length==0&&this.fillStyle)this.drawCircle(a)};Actor.prototype.drawExplosion=function(a){var b=this.explosion;a.save();a.fillStyle="rgba(255, 0, 0, 0.7)";a.beginPath();a.arc(0,0,b,0,Math.PI2,false);a.fill();a.restore()};Actor.prototype.draw=function(a){if(this.isGone)return;a.save();a.translate(this.x,this.y);if(0<this.explosion)this.drawExplosion(a);else this.drawNormal(a);a.restore()};
Actor.prototype.isHit=function(a){if(this.isGone||0<this.explosion||0<a.explosion)return false;if(this.region.isHit(a.region)){this.fate(a);a.fate(this);return true}return false};Actor.prototype.calcDistance=function(a){var b=this.x-a.x;var c=this.y-a.y;return Math.sqrt(b*b+c*c)};
Actor.prototype.fate=function(a){if(this.isGone||this.explosion)return;this.hitPoint--;if(0<this.hitPoint){this.absorb(a);return}this.explosion=Actor.MAX_EXPLOSION;var b=Field.Instance.calcPan(this.x);AudioMixer.INSTANCE.play(this.sfx,.2,false,b)};
Actor.prototype.absorb=function(a){this.absorbed=true;if(this.sfxAbsorb){var b=Field.Instance.ctx;b.fillStyle="rgba(255, 200, 0, 0.4)";b.save();b.translate(a.x,a.y);b.beginPath();b.arc(0,0,5,0,Math.PI2,false);b.fill();b.restore();var c=Field.Instance.calcPan(this.x);AudioMixer.INSTANCE.play(this.sfxAbsorb,.3,false,c)}};$jscomp.global.Object.defineProperties(Actor.prototype,{anim:{configurable:true,enumerable:true,set:function(a){if(Array.isArray(a))this.animList=a;else this.animList=[a]}}});
Actor.MAX_EXPLOSION=12;Actor.DEG_STEP=Math.PI/180;var Animator=function(a,b,c,d,e){c=c===undefined?Animator.TYPE.ROTATION:c;d=d===undefined?1:d;e=e===undefined?1:e;this.actor=a;this.type=c;this.numX=d;this.numY=e;this.patNum=0;this.loadImage(a,b)};
Animator.prototype.loadImage=function(a,b){var c=this;var d=ImageManager.Instance;this.img=d.dic[b];if(this.img){this.width=this.img.width/this.numX;this.height=this.img.height/this.numY;this.hW=this.width/2;this.hH=this.height/2;a.width=this.width;a.height=this.height;a.recalculation();return}ImageManager.Instance.reserve([b]);this.img=new Image;this.img.onload=function(){c.width=c.img.width/c.numX;c.height=c.img.height/c.numY;c.hW=c.width/2;c.hH=c.height/2;a.width=c.width;a.height=c.height;a.recalculation()};
this.img.src="img/"+b};
Animator.prototype.next=function(a){if(this.type&Animator.TYPE.V&&.1<Math.abs(this.patNum))if(this.patNum<0)this.patNum+=.1;else this.patNum-=.1;if(a!=null)if(this.type&Animator.TYPE.X){this.patNum+=Math.cos(a)*.5;var b=Math.floor(this.patNum);if(b<0)this.patNum=this.numX-.1;else if(this.numX<=b)this.patNum=0}else if(this.type&Animator.TYPE.Y){this.patNum+=Math.sin(a)*.5;var c=Math.floor(this.patNum);if(c<0)this.patNum=this.numY-.1;else if(this.numY<=c)this.patNum=0}else if(this.type&Animator.TYPE.V){var d=
Math.floor(this.numY/2);this.patNum+=Math.sin(a)/3;if(this.patNum<-d)this.patNum=-d;else if(d<this.patNum)this.patNum=d}this.patNum*=1E3;this.patNum=Math.round(this.patNum)/1E3};
Animator.prototype.draw=function(a){var b=this.actor;var c=this.width;var d=this.height;var e=0;var f=0;if(this.type&Animator.TYPE.X)e=c*Math.floor(this.patNum);else if(this.type&Animator.TYPE.Y)f=d*Math.floor(this.patNum);else if(this.type&Animator.TYPE.V)f=d*(parseInt(this.patNum)+(this.numY?parseInt(this.numY/2):0));a.save();if(this.type==Animator.TYPE.NONE&&b.isInverse)a.rotate(Math.PI);if(this.type&Animator.TYPE.ROTATION)a.rotate(b.radian);if(b.scale)a.scale(b.scale,b.scale);a.drawImage(this.img,
e,f,c,d,-this.hW,-this.hH,c,d);a.restore()};Animator.TYPE={NONE:0,ROTATION:1,X:2,Y:4,XY:6,H:8,V:16};function AudioMixer(){Repository.apply(this,arguments);this.type="arraybuffer";this.ctx=null;if(window.AudioContext||window.webkitAudioContext)this.ctx=new (window.AudioContext||window.webkitAudioContext);this.dic=[];this.bgm=[];this.lastKey=null;this.lastTime=null}AudioMixer.prototype=Object.create(Repository.prototype);AudioMixer.INSTANCE=new AudioMixer;
AudioMixer.prototype.makeName=function(a){var b=navigator.userAgent.toLowerCase();if(b.indexOf("edge")!==-1||b.indexOf("safari")!==-1)return"audio/"+a+".mp3";return"audio/"+a+".webm"};AudioMixer.prototype.onload=function(a,b,c){var d=this;if(this.ctx===null){this.done();return}this.ctx.decodeAudioData(c,function(e){d.dic[a]=e;d.done()})};
AudioMixer.prototype.play=function(a){if(this.ctx===null||!this.dic[a])return;var b=this;var c=arguments.length;var d=1<c?arguments[1]:1;var e=2<c?arguments[2]:false;var f=3<c?arguments[3]:0;var h=4<c?arguments[4]:0;var g=this.dic[a];var k=new AudioElement(this.ctx,g,h);if(e){k.source.loopEnd=g.duration-.05;k.source.loop=true;this.bgm.push(k);this.lastKey=a}k.gainNode.gain.value=d;k.setPan(f);this.lastTime=this.ctx.currentTime-h};AudioMixer.prototype.setPan=function(a){this.bgm.forEach(function(b){b.setPan(a)})};
AudioMixer.prototype.fade=function(){this.bgm.forEach(function(a){a.fade()})};AudioMixer.prototype.stop=function(){this.bgm.forEach(function(a){a.stop()})};AudioMixer.prototype.getCurrentTime=function(){if(0<this.bgm.length){var a=[];this.bgm.forEach(function(b){if(!b.done)a.push(b)});this.bgm=a}if(!this.bgm.length)return null;return this.ctx.currentTime-this.lastTime};AudioMixer.prototype.setCurrentTime=function(a){if(!this.bgm.length)return;this.stop();this.play(this.lastKey,1,true,0,a)};
function AudioElement(a,b,c){var d=this;this.done=false;this.source=a.createBufferSource();this.gainNode=a.createGain();this.gainNode.connect(a.destination);if("function"==typeof a.createStereoPanner){this.panNode=a.createStereoPanner();this.panNode.connect(this.gainNode);this.source.connect(this.panNode)}else{this.panNode=null;this.source.connect(this.gainNode)}this.source.buffer=b;this.source.start(0,c);this.source.onended=function(){d.done=true}}
AudioElement.prototype.setPan=function(a){if(this.panNode)this.panNode.pan.value=a};AudioElement.prototype.fade=function(){var a=this;var b=this.gainNode.gain;var c=b.value;var d=function(){if(Math.floor(c*100)==0){a.stop();return}c*=.9;b.value=c;setTimeout(d,600)};d()};AudioElement.prototype.stop=function(){if(!this.done)this.source.stop()};var Bullet=function(a,b){Actor.call(this,a,b);this.region=new Region(this,2);this.speed=2;this.width=4;this.fillStyle="rgba(120, 200, 255, 0.7)";this.recalculation()};$jscomp.inherits(Bullet,Actor);Bullet.DEG_STEP=Actor.DEG_STEP;Bullet.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Bullet.prototype.move=function(a){Actor.prototype.move.call(this,a);if(this.walled){this.eject();return}};var Capsule=function(a){Actor.call(this,a.x,a.y,-1);this.region=new Region(this,8);this.speed=0};$jscomp.inherits(Capsule,Actor);Capsule.DEG_STEP=Actor.DEG_STEP;Capsule.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Capsule.prototype.move=function(a){Actor.prototype.move.call(this,a);if(this.region.isHit(a.region))this.fate(a)};Capsule.RANGE=20;var Chamber=function(a,b,c,d){c=c===undefined?Number.MAX_SAFE_INTEGER:c;d=d===undefined?{}:d;this.type=a;this.cycle=b;this.max=c;this.opt=d;this.reset()};Chamber.prototype.reset=function(){this.tick=0;this.hands=[]};Chamber.prototype.probe=function(){var a=[];this.hands.forEach(function(b){if(!b.isGone)a.push(b)});this.hands=a;this.tick++};
Chamber.prototype.fire=function(a,b){b=b===undefined?null:b;if(this.tick<this.cycle||this.max<=this.hands.length)return null;var c=a.x;var d=a.y;var e=new this.type(c,d,this.opt);if(b){var f=a.calcDistance(b);var h=Field.Instance.stage.getFg();var g=f/e.speed*h.speed;var k=b.x-a.x+g;var l=b.y-a.y;e.dir=Math.atan2(l,k)}this.tick=0;this.hands.push(e);return e};var Controller=function(a){a=a===undefined?false:a;this.keys={};this.point={};this.touch=false;this.init(a);Controller.Instance=this};Controller.prototype.init=function(a){if(!a)window.addEventListener("contextmenu",function(b){b.preventDefault()});this.initKeys();this.initPointingDevice();this.initGameOverPanel()};
Controller.prototype.initKeys=function(){var a=this;window.addEventListener("keydown",function(b){if(b.key)a.keys[b.key]=true;else a.keys["k"+b.keyCode]=true});window.addEventListener("keyup",function(b){if(b.key)delete a.keys[b.key];else delete a.keys["k"+b.keyCode]})};
Controller.prototype.initPointingDevice=function(){var a=this;var b=document.getElementById("canvas");var c=function(e,f){var h=Field.Instance;if(h){var g=h.scale;a.point={x:e/g,y:f/g}}};var d=function(){a.touch=false;a.point=null};b.addEventListener("mousedown",function(e){a.touch=true;a.point={x:e.offsetX,y:e.offsetY}});b.addEventListener("mousemove",function(e){if(a.touch)a.point={x:e.offsetX,y:e.offsetY}});b.addEventListener("mouseup",function(){return d()});b.addEventListener("mouseleave",function(){return d()});
b.addEventListener("touchstart",function(e){var f=e.touches[0];a.touch=true;c(f.pageX,f.pageY);e.preventDefault()});b.addEventListener("touchmove",function(e){var f=e.touches[0];a.touch=true;c(f.pageX,f.pageY)});b.addEventListener("touchend",function(){return d()})};
Controller.prototype.initGameOverPanel=function(){var a=this;var b=document.getElementById("gameOver");if(b){var c=function(){Field.Instance.startGame();b.classList.add("hidden")};b.addEventListener("mousedown",function(d){c()});window.addEventListener("keydown",function(d){var e=!b.classList.contains("hidden");if(e&&(a.keys[" "]||a.keys["k32"]))c()})}};var Enemy=function(a,b,c){c=c===undefined?0:c;Actor.call(this,a,b,c);this.radian=Math.PI;this.routine=null;this.routineIx=0;this.routineCnt=0;this.chamberList=[new Chamber(Bullet,Enemy.TRIGGER_CYCLE)]};$jscomp.inherits(Enemy,Actor);Enemy.DEG_STEP=Actor.DEG_STEP;Enemy.MAX_EXPLOSION=Actor.MAX_EXPLOSION;
Enemy.prototype.move=function(a){if(this.routine){var b=this.routine[this.routineIx];b.tick(this,a)}var c=Actor.prototype.move.call(this,a);if(!(a instanceof Enemy)&&this.calcDistance(a)<Enemy.TRIGGER_ALLOWANCE)c=[];return c};Enemy.TRIGGER_CYCLE=50;Enemy.TRIGGER_ALLOWANCE=100;Enemy.MAX_TYPE=127;Enemy.LIST=[];Enemy.assign=function(a,b,c){var d=Object.assign({},Enemy.LIST[a%Enemy.LIST.length]);d.x=b;d.y=c;return d};var Chain=function(a,b){Enemy.call(this,a,b);this.prev=null;this.next=null};
$jscomp.inherits(Chain,Enemy);Chain.DEG_STEP=Enemy.DEG_STEP;Chain.MAX_EXPLOSION=Enemy.MAX_EXPLOSION;Chain.assign=Enemy.assign;Chain.LIST=Enemy.LIST;Chain.MAX_TYPE=Enemy.MAX_TYPE;Chain.TRIGGER_ALLOWANCE=Enemy.TRIGGER_ALLOWANCE;Chain.TRIGGER_CYCLE=Enemy.TRIGGER_CYCLE;Chain.prototype.unshift=function(a){a.next=this;a.prev=this.prev;if(this.prev)this.prev.next=a;this.prev=a;return this};Chain.prototype.push=function(a){a.prev=this;a.next=this.next;if(this.next)this.next.prev=a;this.next=a;return this};
Chain.prototype.remove=function(){this.prev.next=this.next;this.next.prev=this.prev;return this.next};var Field=function(a,b){Matter.call(this,0,0);this.width=a;this.height=b;this.ship=new Ship(-100,100);this.ship.isGone=true;this.shipRemain=0;this.actorList=[];this.score=0;this.hiscore=0;this.enemyCycle=0;this.stage=Stage.LIST[0];this.stageNum=0;this.setup();Field.Instance=this};$jscomp.inherits(Field,Matter);Field.prototype.setup=function(){var a=document.getElementById("canvas");a.width=this.width;a.height=this.height;this.ctx=a.getContext("2d");this.landform=new Landform(a);this.resize()};
Field.prototype.resize=function(){var a=document.body.clientWidth/this.width;var b=window.innerHeight/this.height;var c=document.getElementById("view");this.scale=b<a?b:a;c.setAttribute("style","transform: scale("+this.scale+");")};Field.prototype.nextStage=function(){var a=Stage.LIST[this.stageNum];this.stage=a;this.landform.loadStage(a);this.stageNum++;if(Stage.LIST.length<=this.stageNum)this.stageNum=0};
Field.prototype._reset=function(){this.phase=Field.PHASE.NORMAL;this.ship.reset();this.ship.x=100;this.ship.y=100;this.ship.enter();this.actorList=[this.ship];this.hibernate=Field.MAX_HIBERNATE};Field.prototype.reset=function(){this.landform.reset();this._reset()};Field.prototype.retry=function(){this.landform.retry();this._reset()};Field.prototype.startGame=function(){this.loosingRate=Field.MAX_LOOSING_RATE;this.score=0;this.shipRemain=Field.MAX_SHIP;this.stageNum=0;this.nextStage();this._reset()};
Field.prototype.endGame=function(){var a=document.getElementById("gameOver");a.classList.remove("hidden")};Field.prototype.isGameOver=function(){var a=document.getElementById("gameOver");return!a.classList.contains("hidden")};Field.prototype.calcPan=function(a){return(a-this.hW)/this.hW};
Field.prototype.move=function(){var a=this;if(this.phase==Field.PHASE.BOSS)return;this.landform.scanEnemy().forEach(function(d){var e;if(d.formation)e=(new Formation(d.x,d.y)).setup(d.type,8);else e=new d.type(d.x,d.y);a.actorList.push(e)});var b=this.landform.forward(this.ship);if(this.isGameOver())return;if(b==Landform.NEXT.NOTICE){AudioMixer.INSTANCE.fade();this.stage.notice()}else if(b==Landform.NEXT.ARRIV){this.phase=Field.PHASE.BOSS;this.stage.toBossMode()}else if(b==Landform.NEXT.PAST)this.nextStage();
if(Field.MIN_LOOSING_RATE<this.loosingRate){var c=this.loosingRate/1E4;this.loosingRate-=c}};
Field.prototype.draw=function(){var a=this;var b=this.ctx;var c=this.ship;var d=[];var e=[];var f=[];var h=0;b.clearRect(0,0,this.width,this.height);this.landform.drawBg(b);this.actorList.sort(function(g,k){return g.z-k.z});this.actorList.forEach(function(g){if(g.isGone)return;if(g instanceof Bullet)g.isHit(c);else if(g instanceof Enemy){g.triggered=parseInt(Math.random()*a.loosingRate/10)==0;g.isHit(c);e.push(g)}else if(g instanceof Shot||g instanceof Missile)d.push(g);var k=g.move(c);if(k instanceof
Array)k.forEach(function(l){f.push(l)});a.landform.effect(g);a.landform.hitTest(g);g.draw(b);f.push(g);if(g.explosion&&g.score){h+=g.score;g.score=0}});d.forEach(function(g){e.forEach(function(k){return k.isHit(g)})});if(this.phase==Field.PHASE.BOSS&&e.length==0){this.phase=Field.PHASE.NORMAL;AudioMixer.INSTANCE.fade()}this.actorList=f;this.landform.draw();this.score+=h;this.showScore();if(!this.isGameOver()&&c.isGone){AudioMixer.INSTANCE.stop();if(0<--this.hibernate)return;if(0<--this.shipRemain)this.retry();
else this.endGame()}};
Field.prototype.showScore=function(){if(this.hiscore<this.score)this.hiscore=this.score;var a=document.querySelector("#score \x3e div \x3e div:nth-child(2)");var b=document.querySelector("#score \x3e div:nth-child(2) \x3e div:nth-child(2)");var c=document.querySelector("#score \x3e div:nth-child(3)");var d=document.querySelector("#remain \x3e div \x3e div:nth-child(1)");if(!a)return;a.innerHTML=this.score;b.innerHTML=this.hiscore;if(this.shipRemain)d.style.width=(this.shipRemain-1)*16+"px"};
Field.MAX_ENEMIES=100;Field.ENEMY_CYCLE=10;Field.MIN_LOOSING_RATE=1;Field.MAX_LOOSING_RATE=2E4;Field.MAX_SHIP=7;Field.MAX_HIBERNATE=Actor.MAX_EXPLOSION*5;Field.PHASE={NORMAL:0,BOSS:1};var Formation=function(a,b){Actor.call(this,a,b);this.effectH=false;this.steps=0;this.count=0;this.enemies=[]};$jscomp.inherits(Formation,Actor);Formation.DEG_STEP=Actor.DEG_STEP;Formation.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Formation.prototype.setup=function(a,b){for(var c=0;c<b;c++){var d=new a(this.x,this.y);if(!this.bonus){this.score=d.score*10;this.bonus=this.score}this.enemies.push(d)}return this};
Formation.prototype.isDestroyed=function(){var a=this;var b=[];this.enemies.forEach(function(c){if(c.hitPoint==0)return;b.push(c);a.x=c.x;a.y=c.y});this.enemies=b;if(b.length==0&&this.explosion==0){this.explosion=Actor.MAX_EXPLOSION*4;return true}return false};
Formation.prototype.move=function(a){Actor.prototype.move.call(this,a);if(this.enemies.length<=this.count){if(this.isDestroyed()){var b=[SpeedupCapsule,MissileCapsule];var c=Math.floor(Math.random()*b.length);var d=b[c];return[new d(this)]}return}if(this.steps++%Formation.STEP!=0)return;return[this.enemies[this.count++]]};Formation.prototype.drawExplosion=function(a){a.fillStyle="rgba(240, 240, 255, .8)";a.fillText(this.bonus,0,0)};Formation.STEP=10;var ImageManager=function(){this.max=0;this.loaded=0;this.dic={}};ImageManager.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};ImageManager.prototype.reserve=function(a){var b=this;a.forEach(function(c){if(c in b.dic)return;var d=new Image;d.onload=function(){b.dic[c]=d;b.loaded++};d.src="img/"+c;b.max++})};ImageManager.Instance=new ImageManager;var Landform=function(a,b){b=b===undefined?false:b;var c=this;this.canvas=a;this.ctx=a.getContext("2d");this.isEdit=b;this.effectH=0;this.next=Landform.NEXT.NONE;this.col=0;this.colDir=1;this.magni=1;this.target=null;this.tx=0;this.ty=0;this.selection="b0";this.which=null;this.brick=null;this.brickVal=null;this.lastScan=null;this.touch=false;this.img=new Image;this.img.onload=function(){var d=Field.Instance;c.width=c.img.width;c.height=c.img.height;c.bw=c.img.width/Landform.BRICK_WIDTH;c.bh=c.img.height/
Landform.BRICK_WIDTH;if(d){c.viewX=c.img.width-d.hW*1.5;c.arrivX=c.img.width-d.width;c.noticeX=c.arrivX-d.hW}};this.reverse=new Image;this.reverse.src="./img/reverse.png";this.touch=false};Landform.BRICK_WIDTH=8;Landform.BRICK_HALF=Landform.BRICK_WIDTH/2;Landform.BRICK_TYPE={WALL:255,BRITTLE:254};Landform.COL_MAX=512;Landform.NEXT={NONE:0,NOTICE:1,ARRIV:2,IDLE:3,PAST:4};Landform.prototype.load=function(a){if(a instanceof File)this.img.src=window.URL.createObjectURL(a)};
Landform.prototype.loadMapData=function(a){var b=this;var c=new Image;c.onload=function(){var d=document.createElement("canvas");var e=d.getContext("2d");d.width=this.width;d.height=this.height;e.drawImage(c,0,0);b.brick=e.getImageData(0,0,this.width,this.height);b.touch=true};if(a instanceof File)c.src=window.URL.createObjectURL(a);else c.src=a};Landform.prototype.loadStage=function(a){var b=a.getFg();this.stage=a;this.loadMapData("./img/"+a.map);this.img.src=b.img.src;this.reset()};
Landform.prototype.reset=function(){this.next=Landform.NEXT.NONE;if(this.stage)this.stage.reset()};Landform.prototype.retry=function(){this.next=Landform.NEXT.NONE;if(this.stage){this.stage.retry();this.loadMapData("./img/"+this.stage.map)}};
Landform.prototype.effect=function(a){var b=Math.max(Field.Instance.width+a.width,a.maxX);if(a.effectH)a.x-=this.effectH;if(a.effectV&&this.next==Landform.NEXT.NONE){var c=this.stage.getFg().speed;a.y+=this.stage.effectV*c}if(a.x<a.minX||b<a.x)a.eject();if(this.stage.scroll==Stage.SCROLL.OFF){if(a.y<a.minY||a.maxY<a.y)a.eject();return}if(this.stage.scroll==Stage.SCROLL.ON){if(a.y<-this.height||this.height+a.maxY<a.y)a.eject();return}if(a.gravity){var d=Math.abs(a.dy*a.speed);if(Landform.BRICK_WIDTH+
Landform.BRICK_HALF<d){a.eject();return}}if(a.y<0)a.y+=this.height;else if(this.height<a.y)a.y-=this.height};
Landform.prototype.forward=function(a){if(!this.width)return Landform.NEXT.NONE;var b=this.stage.getFg();if(this.next!=Landform.NEXT.ARRIV)this.stage.scrollV(a);if(this.viewX<=b.x){this.effectH=0;if(this.next!=Landform.NEXT.PAST){this.next=Landform.NEXT.PAST;return Landform.NEXT.PAST}return Landform.NEXT.NONE}this.stage.forward();this.effectH=b.effectH;if(this.arrivX<=b.x){if(this.next==Landform.NEXT.NOTICE){b.x=this.arrivX;this.effectH=0;this.next=Landform.NEXT.ARRIV;return Landform.NEXT.ARRIV}if(this.arrivX<
b.x){this.next=Landform.NEXT.IDLE;return Landform.NEXT.IDLE}}else if(this.noticeX<=b.x)if(this.next!=Landform.NEXT.NOTICE){this.next=Landform.NEXT.NOTICE;return Landform.NEXT.NOTICE}return Landform.NEXT.NONE};
Landform.prototype.scanEnemy=function(){var a=[];if(!this.brick||this.next==Landform.NEXT.IDLE)return a;var b=Field.Instance;var c=this.stage.getFg();var d=c.x;var e=c.y;var f=Math.round((d+b.width-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(f<0)return a;if(f===this.lastScan)return a;this.lastScan=f;var h=b.width+Landform.BRICK_WIDTH;for(var g=0;g<this.bh;g++){var k=g*this.bw*4+f*4;var l=this.brick.data[k+1];if(0<l&&l<=Enemy.MAX_TYPE){var n=-e+(g+1)*Landform.BRICK_WIDTH;a.push(Enemy.assign(l-1,
h,n))}}f=Math.round(d/Landform.BRICK_WIDTH);if(f<0)return a;for(var m=0;m<this.bh;m++){var p=m*this.bw*4+f*4;var q=this.brick.data[p+1];if(Enemy.MAX_TYPE<q){var r=-e+(m+1)*Landform.BRICK_WIDTH;a.push(Enemy.assign(q-1-Enemy.MAX_TYPE,0,r))}}return a};Landform.prototype.hitTest=function(a){if(!this.brick)return;a.walled=this.getBrick(a,2);this.target=a};Landform.prototype.smashWall=function(a){var b=this.stage.getFg();b.smashWall(a);this.putBrick(a,2,0)};
Landform.prototype.scanFloor=function(a){if(!this.brick)return;var b=a.y;var c=this.getBrick(a,2);var d=a.gravity<0?-1:1;if(0<c){for(b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;0<c;){b-=Landform.BRICK_WIDTH*d;var e={x:a.x,y:b};c=this.getBrick(e,2)}b+=Landform.BRICK_WIDTH*d}else{b=Math.floor(a.y/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;if(d<0){for(;0<b&&!c;){b-=Landform.BRICK_WIDTH;var f={x:a.x,y:b};c=this.getBrick(f,2)}if(!c)b=-a.height-Landform.BRICK_WIDTH}else{for(;b<this.height&&
!c;){b+=Landform.BRICK_WIDTH;var h={x:a.x,y:b};c=this.getBrick(h,2)}if(!c)b=this.height+a.height+Landform.BRICK_WIDTH}}return b};Landform.prototype.getHorizontalAngle=function(a){var b={x:a.x-Landform.BRICK_WIDTH,y:a.y-Landform.BRICK_WIDTH*2};var c={x:a.x+Landform.BRICK_WIDTH,y:a.y-Landform.BRICK_WIDTH*2};var d=this.scanFloor(b);var e=this.scanFloor(c);return Math.atan2(e-d,a.width)};
Landform.prototype.getBrickIndex=function(a){var b=this.stage.getFg();var c=b.x;var d=b.y;var e=Math.round((c+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);if(e<0||this.bw<e)return-1;var f=Math.round((d+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH);f%=this.bh;return f*this.bw*4+e*4};Landform.prototype.getBrick=function(a,b){if(!this.brick)return null;var c=this.getBrickIndex(a);if(c<0)return null;return this.brick.data[c+b]};
Landform.prototype.wheel=function(a){var b=this.stage.getFg();if(a<0){b.y+=Landform.BRICK_WIDTH*2;if(this.height<=b.y)b.y=0}else{if(b.y==0)b.y=this.height;b.y-=Landform.BRICK_WIDTH*2}};Landform.prototype.putBrick=function(a,b,c){var d=this.getBrickIndex(a);if(d<0)return;this.brick.data[d+b]=c;this.brick.data[d+3]=c?255:0};
Landform.prototype.drawEnemy=function(a,b,c){var d=Enemy.MAX_TYPE<a;var e=d?a-Enemy.MAX_TYPE:a;var f=Enemy.LIST[e-1];var h=f.formation?3:1;var g=f.instance;var k=this.ctx;if(!f.instance)return null;g.x=b+g.hW;for(g.y=c+g.hH;h--;){g.draw(k);g.x+=2;g.y+=2}if(d){k.save();k.translate(g.x,g.y);k.drawImage(this.reverse,-8,-4);k.restore()}return g};
Landform.prototype.drawTarget=function(){if(!this.isEdit||!this.target)return;var a=Math.round((this.target.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var b=Math.round((this.target.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var c=this.ctx;var d=Landform.BRICK_WIDTH;var e=parseInt(this.selection);if(0<e){var f=this.drawEnemy(e,a,b);if(f)d=f.width}c.save();c.fillStyle="rgba(128, 255, 255, .4)";c.fillRect(a,b,d,d);c.restore();this.touchDown(a,b)};
Landform.prototype.touchDown=function(a,b){if(!this.which){this.tx=-1;this.ty=-1;this.brickVal=null;return}if(this.tx==a&&this.ty==b)return;var c=parseInt(this.selection);if(0<c){var d=this.getBrick(this.target,1);var e=d-Enemy.MAX_TYPE;if(!d||d!=c&&e!=c)this.putBrick(this.target,1,c);else if(d==c)this.putBrick(this.target,1,c+Enemy.MAX_TYPE);else this.putBrick(this.target,1,0)}else{var f=this.getBrick(this.target,2);c=this.selection.substr(1);if(this.brickVal==null)this.brickVal=0<f?0:255-c;this.putBrick(this.target,
2,this.brickVal)}this.touch=true;this.tx=a;this.ty=b};
Landform.prototype.drawBrick=function(){if(!this.brick||!this.isEdit)return;var a=Field.Instance;var b=this.stage.getFg();var c=b.x;var d=b.y;var e=this.ctx;var f=255<this.col?this.col-256:0;var h=255<this.col?255:this.col%256;var g=Landform.BRICK_WIDTH-2;var k=Math.round(c/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var l=k/Landform.BRICK_WIDTH;var n=Math.min(l+512/Landform.BRICK_WIDTH,this.bw);var m=Math.round(d/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var p=m/Landform.BRICK_WIDTH;var q=this.brick.data;
e.save();e.translate(-c,-d);e.strokeStyle="rgba("+f+", "+h+", 255, .4)";e.fillStyle=e.strokeStyle;for(var r=0;r<this.bh;r++){var x=p+r;var u=x*Landform.BRICK_WIDTH;var v=(x%this.bh*this.bw+l)*4;var w=l;for(var t=k;w<n;w++,t+=Landform.BRICK_WIDTH,v+=4){if(w<0)continue;var y=q[v+1];if(y)this.drawEnemy(y,t,u);var z=q[v+2];if(z==255)e.fillRect(t,u,g,g);else if(z==254){var A=t+Landform.BRICK_HALF-1;var B=u+Landform.BRICK_HALF-1;e.beginPath();e.arc(A,B,g/2,0,Math.PI2,false);e.stroke();e.strokeRect(t,u,
g,g)}}}if(this.width-a.width<=c){var C=this.width-Landform.BRICK_WIDTH;e.fillStyle="rgba(255, 0, 0, .4)";e.fillRect(C,0,Landform.BRICK_WIDTH,this.height)}e.restore();this.col+=this.colDir*16;if(this.col<=0||Landform.COL_MAX<=this.col)this.colDir*=-1};Landform.prototype.drawBg=function(a){if(!this.stage)return;a.save();a.scale(this.magni,this.magni);this.stage.drawBg(a);a.restore()};
Landform.prototype.draw=function(){if(!this.stage)return;var a=this;var b=this.ctx;b.save();b.scale(this.magni,this.magni);this.stage.drawFg(b);this.drawBrick();this.drawTarget();b.restore();if(!this.brick||!this.isEdit)return;if(this.touch&&this.brick){this.updateMap();this.touch=false}};
Landform.prototype.updateMap=function(){var a=document.getElementById("mapImage");if(a){var b=document.createElement("canvas");var c=b.getContext("2d");b.width=this.brick.width;b.height=this.brick.height;c.putImageData(this.brick,0,0);a.setAttribute("src",b.toDataURL("image/png"))}};Landform.prototype.getImageData=function(){var a=document.createElement("canvas");var b=a.getContext("2d");a.width=this.width;a.height=this.height;b.drawImage(this.img,0,0);return b.getImageData(0,0,this.width,this.height)};
Landform.prototype.getBrickData=function(a){if(this.brick!=null)return this.brick;var b=this.width/Landform.BRICK_WIDTH;var c=this.height/Landform.BRICK_WIDTH;return a.createImageData(b,c)};
Landform.prototype.generateBrick=function(a){if(!this.img.src||!this.img.complete)return;var b=this.getImageData();var c=this.width/Landform.BRICK_WIDTH;var d=this.height/Landform.BRICK_WIDTH;var e=this.getBrickData(a);var f=e.data;var h=this.width*Landform.BRICK_HALF+Landform.BRICK_HALF*4;var g=0;console.log(this.width+" x "+this.height+" | "+this.width*this.height*4);console.log(c+" x "+d+" | "+f.length);for(var k=0;k<d;k++){for(var l=0;l<c;l++){var n=false;for(var m=0;m<4;m++)if(b.data[h+m])n=
true;var p=n?255:0;f[g+2]=p;f[g+3]=p;h+=Landform.BRICK_WIDTH*4;g+=4}h+=this.width*(Landform.BRICK_WIDTH-1)*4}console.log("ix:"+g);console.log("sx:"+h);this.brick=e;this.touch=true};Math.PI2=Math.PI2||Math.PI*2;Math.SQ=Math.SQ||Math.PI/2;Math.trim=Math.trim||function(a){for(var b=a;Math.PI<b;)b-=Math.PI2;for(;b<-Math.PI;)b+=Math.PI2;return b};Math.close=Math.close||function(a,b,c){var d=Math.trim(a-b);if(Math.abs(d)<=c)return a;if(0<d)return a-c;return a+c};function Matrix(a){this.mat=a}Matrix.NO_EFFECT=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]];Matrix.rotateX=function(a){return new Matrix([[1,0,0,0],[0,Math.cos(a),-Math.sin(a),0],[0,Math.sin(a),Math.cos(a),0],[0,0,0,1]])};Matrix.rotateY=function(a){return new Matrix([[Math.cos(a),0,Math.sin(a),0],[0,1,0,0],[-Math.sin(a),0,Math.cos(a),0],[0,0,0,1]])};Matrix.rotateZ=function(a){return new Matrix([[Math.cos(a),-Math.sin(a),0,0],[Math.sin(a),Math.cos(a),0,0],[0,0,1,0],[0,0,0,1]])};
Matrix.prototype.multiply=function(a){var b=[[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];var c=a.mat;this.mat.forEach(function(d,e){d.forEach(function(f,h){var g=0;for(var k=0;k<4;k++)g+=d[k]*c[k][h];b[e][h]=g})});return new Matrix(b)};Matrix.prototype.affine=function(a,b,c){var d=this.mat;var e=d[0][0]*a+d[0][1]*b+d[0][2]*c+d[0][3];var f=d[1][0]*a+d[1][1]*b+d[1][2]*c+d[1][3];var h=d[2][0]*a+d[2][1]*b+d[2][2]*c+d[2][3];return{x:e,y:f,z:h}};var Missile=function(a,b,c){Actor.call(this,a,b);this.dir=c.dir;this.speed=3;this.width=2.5;this.gravity=c.gravity;this.recalculation();this.shuttle=3;this.fillStyle="rgba(200, 200, 255, 0.6)"};$jscomp.inherits(Missile,Actor);Missile.DEG_STEP=Actor.DEG_STEP;Missile.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Missile.prototype.reactX=function(a){Actor.prototype.reactX.call(this,a);this.shuttle--;if(this.shuttle<0)this.fate()};Missile.prototype.fate=function(){this.eject()};function Gizmo(a,b,c){c=c===undefined?null:c;this.type=a;this.destination=b;this.param=c}Gizmo.TYPE={FIXED:0,OWN:1,AIM:2,CHASE:3};Gizmo.DEST={TO:0,TO_X:1,TO_Y:2,ROTATE:3,ROTATE_L:4,ROTATE_R:5,LEFT:6,RIGHT:7};
Gizmo.prototype.tick=function(a,b){var c=Field.Instance.landform;if(this.type==Gizmo.TYPE.FIXED){if(this.destination==Gizmo.DEST.ROTATE)a.radian=a.dir;else a.dir=null;return}if(this.type==Gizmo.TYPE.OWN){if(this.destination==Gizmo.DEST.ROTATE_L)a.dir-=a.step;else if(this.destination==Gizmo.DEST.ROTATE_R)a.dir+=a.step;else if(this.destination==Gizmo.DEST.LEFT)a.dir=Math.PI;else if(this.destination==Gizmo.DEST.RIGHT)a.dir=0;return}var d=b.x-a.x;var e=b.y-a.y;if(Math.abs(d)<=a.speed)d=0;if(Math.abs(e)<=
a.speed)e=0;if(this.type==Gizmo.TYPE.AIM){if(this.destination==Gizmo.DEST.TO_X)if(d<0)a.radian=Math.PI;else a.radian=0;else if(this.destination==Gizmo.DEST.TO_Y)if(d<0)a.radian=-Math.SQ;else a.radian=Math.SQ;else if(this.destination==Gizmo.DEST.ROTATE){var f=a.calcDistance(b);if(a.speed<f){var h=this.param?this.param:Math.PI/30;a.radian=Math.close(a.radian,Math.atan2(e,d),h);a.radian=Math.trim(a.radian)}}return}if(this.type==Gizmo.TYPE.CHASE)if(this.destination==Gizmo.DEST.TO)a.dir=Math.atan2(e,d);
else if(this.destination==Gizmo.DEST.TO_X&&d)a.dir=Math.atan2(0,d);else if(this.destination==Gizmo.DEST.TO_Y&&e)a.dir=Math.atan2(e,0);else if(this.destination==Gizmo.DEST.ROTATE){var g=this.param?this.param:Math.PI/60;a.dir=Math.close(a.dir,Math.atan2(e,d),g);a.radian=a.dir}};function Movement(a){var b=parseInt(a);this.cond=a;this.count=b==a?b:null;this.list=[]}Movement.COND={X:"x",Y:"y"};Movement.prototype.add=function(a,b,c){this.list.push(new Gizmo(a,b,c));return this};
Movement.prototype.isValid=function(a,b){if(!this.cond)return;if(this.count){if(a.routineCnt++<this.count)return true;a.routineCnt=0;return false}var c=b.x-a.x;var d=b.y-a.y;if(this.cond==Movement.COND.X&&Math.abs(c)<=a.speed)return false;if(this.cond==Movement.COND.Y&&Math.abs(d)<=a.speed)return false;return true};Movement.prototype.tick=function(a,b){this.list.forEach(function(c){c.tick(a,b)});if(!this.isValid(a,b)){a.routineIx++;if(a.routine.length<=a.routineIx)a.routineIx=0}};var Region=function(a,b,c){b=b===undefined?Region.DefaultSize:b;c=c===undefined?Region.Type.CIRCLE:c;this.matter=a;this.size=b;this.type=c;this.width=b*2};Region.prototype.isHit=function(a){if(this.type==Region.Type.CIRCLE)if(a.type==Region.Type.CIRCLE){var b=this.matter.x-a.matter.x;var c=this.matter.y-a.matter.y;var d=Math.sqrt(b*b+c*c);return d<this.size+a.size}console.log("*Not implement*")};
Region.prototype.draw=function(a){a.save();a.strokeStyle="rgba(80, 255, 80, 0.6)";if(this.type==Region.Type.RECTANGLE)a.strokeRect(-this.size,-this.size,this.width,this.width);else{a.beginPath();a.arc(0,0,this.size,0,Math.PI2,false);a.stroke()}a.restore()};Region.DefaultSize=4;Region.Type={CIRCLE:1,RECTANGLE:2};function Repository(){this.max=0;this.loaded=0;this.dic={};this.reserved={};this.type="json"}Repository.prototype.isComplete=function(){return 0<this.max&&this.max==this.loaded};Repository.prototype.reserve=function(a){var b=this;a.forEach(function(c){if(c==null)return;if(c in b.reserved)return;b.reserved[c]=true;b.load(c)})};Repository.prototype.makeName=function(a){return a};
Repository.prototype.load=function(a){var b=this;var c=new XMLHttpRequest;var d=this.makeName(a);this.max++;c.open("GET",d,true);c.responseType=this.type;c.addEventListener("loadend",function(){var e=c.response;b.dic[a]=e;b.onload(a,d,e)});c.send()};Repository.prototype.onload=function(a,b,c){this.done()};Repository.prototype.done=function(){this.loaded++};var Ship=function(a,b){Actor.call(this,a,b);this.effectH=false;this.anim=new Animator(this,"ship001.png",Animator.TYPE.V,1,Ship.PATTERNS*2+1);this.reset()};$jscomp.inherits(Ship,Actor);Ship.DEG_STEP=Actor.DEG_STEP;Ship.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Ship.prototype.recalculation=function(){var a=Field.Instance;Actor.prototype.recalculation.call(this);if(a){this.right=a.width-this.width*2;this.bottom=a.height-this.hH}};
Ship.prototype.reset=function(){this.speed=Ship.MIN_SPEED;this.triggered=false;this.chamberList=[new Chamber(Shot,4,Ship.MAX_SHOTS)];this.chamberList.forEach(function(a){return a.reset()});this.missileLevel=0};Ship.prototype.speedup=function(){this.speed*=1.25;if(Ship.MAX_SPEED<this.speed)this.speed=Ship.MAX_SPEED};
Ship.prototype.powerUpMissile=function(){this.missileLevel++;if(this.missileLevel==1)this.chamberList.push(new Chamber(Missile,16,2,{gravity:.05,dir:0}));else if(this.missileLevel==2)this.chamberList.push(new Chamber(Missile,16,2,{gravity:-.05,dir:0}));else if(this.missileLevel==3){this.chamberList.push(new Chamber(Missile,16,2,{gravity:.05,dir:Math.PI}));this.chamberList.push(new Chamber(Missile,16,2,{gravity:-.05,dir:Math.PI}))}};
Ship.prototype.inkey=function(a){var b=false;var c=0;if(a["ArrowLeft"]||a["Left"]||a["k37"]){c=1;b=true}else if(a["ArrowRight"]||a["Right"]||a["k39"]){c=-1;b=true}if(a["ArrowUp"]||a["Up"]||a["k38"]){c=2-c*.5;b=true}else if(a["ArrowDown"]||a["Down"]||a["k40"]){c*=.5;b=true}if(b)this.dir=(c+1)*Math.SQ;if(a["Control"]||a["Shift"]||a["k16"]||a["k17"])this.triggered=true};
Ship.prototype.move=function(){this.dir=null;this.aim(Controller.Instance.point);this.inkey(Controller.Instance.keys);if(Controller.Instance.touch)this.triggered=true;var a=Actor.prototype.move.call(this);if(this.isGone)return;if(this.walled){this.fate();return}if(this.x<this.hW||this.right<this.x)this.x=this.svX;if(this.y<this.hH||this.bottom<this.y)this.y=this.svY;return a};Ship.MIN_SPEED=1.5;Ship.MAX_SPEED=5;Ship.MAX_SHOTS=7;Ship.PATTERNS=2;var Shot=function(a,b){Actor.call(this,a,b);this.dir=0;this.width=2;this.speed=6;this.size=2;this.maxX=Field.Instance.width;this.fillStyle="rgba(255, 255, 0, 0.7)";var c=Field.Instance.calcPan(this.x);AudioMixer.INSTANCE.play("sfx-fire",.4,false,c)};$jscomp.inherits(Shot,Actor);Shot.DEG_STEP=Actor.DEG_STEP;Shot.MAX_EXPLOSION=Actor.MAX_EXPLOSION;Shot.prototype.fate=function(){this.eject()};
Shot.prototype.move=function(a){Actor.prototype.move.call(this,a);if(this.walled){if(this.walled==Landform.BRICK_TYPE.BRITTLE)Field.Instance.landform.smashWall(this);this.fate()}};var Stage=function(a,b,c){var d=this;this.scroll=a;this.scrollSv=a;this.map=b;this.view=c;this.fg=null;this.bgm=null;this.boss=null;this.checkPoint=0;this.view.forEach(function(e){e.stage=d});this.effectH=0;this.effectV=0};Stage.prototype.setBgm=function(a,b){b=b===undefined?null:b;this.bgm=a;this.boss=b;AudioMixer.INSTANCE.reserve([this.bgm,this.boss]);return this};Stage.prototype.playBgm=function(){if(this.bgm)AudioMixer.INSTANCE.play(this.bgm,.7,true)};
Stage.prototype.getFg=function(){if(this.fg)return this.fg;var a;this.view.forEach(function(b){if(b instanceof StageFg)a=b});this.fg=a;return a};Stage.prototype.reset=function(){this.checkPoint=Stage.CHECK_POINT[0];this.retry()};Stage.prototype.retry=function(){var a=this;this.scroll=this.scrollSv;this.effectH=0;this.effectV=0;this.view.forEach(function(b){b.reset(a.checkPoint)});this.playBgm()};
Stage.prototype.scrollV=function(a){this.effectV=0;if(this.scroll==Stage.SCROLL.OFF)return;var b=Field.Instance;var c=b.hH-a.y;var d=this.getFg();if(this.scroll==Stage.SCROLL.TOP)c=d.speed*5;else if(this.scroll==Stage.SCROLL.BOTTOM)c=-d.speed*5;else if(Math.abs(c)<d.speed)return;var e=c/3;var f=d.y-e;var h=d.height-b.height;if(this.scroll==Stage.SCROLL.ON)if(f<0||h<f)return;if(this.scroll==Stage.SCROLL.TOP&&f<0){this.scroll=Stage.SCROLL.OFF;return}if(this.scroll==Stage.SCROLL.BOTTOM){console.log("nextY:"+
f+"/"+d.height);if(h<f){this.scroll=Stage.SCROLL.OFF;return}}this.effectV=e};Stage.prototype.forward=function(a){var b=this;this.view.forEach(function(d){d.forward(a)});var c=this.getFg().x;Stage.CHECK_POINT.forEach(function(d){if(d<=c&&b.checkPoint<c)b.checkPoint=d})};Stage.prototype.drawBg=function(a){this.view.forEach(function(b){if(b instanceof StageFg)return;b.draw(a)})};Stage.prototype.drawFg=function(a){this.view.forEach(function(b){if(b instanceof StageBg)return;b.draw(a)})};
Stage.prototype.notice=function(){if(this.scroll!=Stage.SCROLL.ON&&this.scroll!=Stage.SCROLL.LOOP)return;var a=this.getFg();if(a.y<a.height/2)this.scroll=Stage.SCROLL.TOP;else this.scroll=Stage.SCROLL.BOTTOM};Stage.prototype.toBossMode=function(){if(this.boss)AudioMixer.INSTANCE.play(this.boss,.7,true)};Stage.SCROLL={OFF:0,ON:1,LOOP:2,TOP:4,BOTTOM:8};Stage.LIST=[];Stage.CHECK_POINT=[0,660,1440];
var StageView=function(a,b,c,d){var e=this;this.ready=false;this.pattern=null;this.repeatX=2;this.img=new Image;this.img.onload=function(){e.width=e.img.width;e.height=e.img.height;e.w2=e.img.width*e.repeatX;e.h2=e.img.height*2;e.ready=true};this.img.src="./img/"+a;this.speed=b;this.dir=c;this.blink=d;this.reset()};StageView.prototype.reset=function(a){this.x=a%this.width;this.y=0;this.effectH=0;this.effectV=0;this.alpha=1;this.blinkDir=-1};
StageView.prototype.forward=function(){var a=this.stage.effectV;this.effectH=Math.cos(this.dir)*this.speed;this.effectV=Math.sin(this.dir)*this.speed;this.x+=this.effectH;this.y+=this.effectV;this.y-=a*this.speed;if(this.width<this.x)this.x-=this.width;if(this.y<0)this.y+=this.height;if(this.height<this.y)this.y-=this.height;if(this.blink){this.alpha+=this.blinkDir*this.blink;if(this.alpha<=.3||1<=this.alpha)this.blinkDir*=-1}};
StageView.prototype.getPattern=function(a,b){if(!this.pattern&&this.ready)this.pattern=a.createPattern(b,"repeat");return this.pattern};StageView.prototype.draw=function(a){a.save();a.globalAlpha=this.alpha;a.translate(-this.x,-this.y);a.beginPath();a.fillStyle=this.getPattern(a,this.img);a.rect(0,0,this.w2,this.h2);a.fill();a.restore()};var StageFg=function(a,b,c,d){b=b===undefined?.5:b;c=c===undefined?0:c;d=d===undefined?0:d;StageView.call(this,a,b,c,d);this.repeatX=1;this.bmp=this.img};
$jscomp.inherits(StageFg,StageView);StageFg.prototype.createCanvas=function(){var a=document.createElement("canvas");var b=a.getContext("2d");a.width=this.width;a.height=this.height;b.clearRect(0,0,this.width,this.height);b.drawImage(this.img,0,0);return a};StageFg.prototype.reset=function(a){var b=this;StageView.prototype.reset.call(this,a);if(a==0)this.x=-Field.Instance.width;if(this.ready){this.canvas=this.createCanvas();this.pattern=canvas.getContext("2d").createPattern(this.canvas,"repeat")}};
StageFg.prototype.smashWall=function(a){var b=Math.round((this.x+a.x-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var c=Math.round((this.y+a.y-Landform.BRICK_HALF)/Landform.BRICK_WIDTH)*Landform.BRICK_WIDTH;var d=this.canvas.getContext("2d");c%=this.height;d.clearRect(b,c,Landform.BRICK_WIDTH,Landform.BRICK_WIDTH);this.pattern=d.createPattern(this.canvas,"repeat")};
var StageBg=function(a,b,c,d){b=b===undefined?.5:b;c=c===undefined?0:c;d=d===undefined?0:d;StageView.call(this,a,b,c,d)};$jscomp.inherits(StageBg,StageView);