-- イメージひな形
delete from image where type = 1;
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.molten', 'boss.molten', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.moltenRock', 'boss.moltenRock', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.head', 'boss.titan.head', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lclavicle', 'boss.titan.lclavicle', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lfemur', 'boss.titan.lfemur', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lfingers', 'boss.titan.lfingers', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lfoot', 'boss.titan.lfoot', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lhand', 'boss.titan.lhand', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lhipjoint', 'boss.titan.lhipjoint', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lhumerus', 'boss.titan.lhumerus', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lowerback', 'boss.titan.lowerback', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lowerneck', 'boss.titan.lowerneck', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lradius', 'boss.titan.lradius', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lthumb', 'boss.titan.lthumb', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.ltibia', 'boss.titan.ltibia', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.ltoes', 'boss.titan.ltoes', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.lwrist', 'boss.titan.lwrist', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rclavicle', 'boss.titan.rclavicle', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rfemur', 'boss.titan.rfemur', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rfingers', 'boss.titan.rfingers', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rfoot', 'boss.titan.rfoot', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rhand', 'boss.titan.rhand', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rhipjoint', 'boss.titan.rhipjoint', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rhumerus', 'boss.titan.rhumerus', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rradius', 'boss.titan.rradius', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rthumb', 'boss.titan.rthumb', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rtibia', 'boss.titan.rtibia', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rtoes', 'boss.titan.rtoes', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.rwrist', 'boss.titan.rwrist', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.thorax', 'boss.titan.thorax', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.titan.ball', 'boss.titan.titan.ball', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.titan.bullet', 'boss.titan.titan.bullet', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.titan.shot', 'boss.titan.titan.shot', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.upperback', 'boss.titan.upperback', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.titan.upperneck', 'boss.titan.upperneck', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.winding.joint', 'boss.winding.joint', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'boss.winding', 'boss.winding', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'capsule.missileCapsule', 'capsule.missileCapsule', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'capsule.speedupCapsule', 'capsule.speedupCapsule', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.battery', 'enemy.battery', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.batteryBase', 'enemy.batteryBase', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.bouncer', 'enemy.bouncer', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.charger', 'enemy.charger', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.crab', 'enemy.crab', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.dragonBody', 'enemy.dragonBody', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.dragonHead', 'enemy.dragonHead', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.hanker', 'enemy.hanker', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.hatch', 'enemy.hatch', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.jerky', 'enemy.jerky', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.juno', 'enemy.juno', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.slur', 'enemy.slur', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.tentacle', 'enemy.tentacle', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.tentacleHead', 'enemy.tentacleHead', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.tentacleJoint', 'enemy.tentacleJoint', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.twister', 'enemy.twister', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'enemy.waver', 'enemy.waver', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'material.cascade', 'material.cascade', '');
insert into image(owner, access, type, content_type, name, description, image) values('SYSTEM', 2, 1, 'image/png', 'prototype.ship', 'prototype.ship', '');
-- アクターひな形
truncate table actor;
insert into actor(owner, access, name, description, imageid)
	select owner, access, name, description, id from image where type=1;

-- オーディオひな形
truncate table audio;
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-edo-beth');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-edo-omega-zero');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-MadNightDance');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-pierrot-cards');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-ThroughTheDark');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 1, 'bgm-YourDream-R');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 0, 'sfx-absorb');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 0, 'sfx-explosion');
insert into audio(owner, access, type, name) values('SYSTEM', 2, 0, 'sfx-fire');

-- プロダクト
INSERT INTO product(name, description, owner) values('Prototype-A', 'This is prototype pattern A.', 'SYSTEM');
INSERT INTO product(name, description, owner) values('Prototype-B', 'This is prototype pattern B.', 'SYSTEM');
INSERT INTO product(name, description, owner) values('Prototype-C', 'This is prototype pattern C.', 'SYSTEM');
